project:
  type: book
  output-dir: docs

bibliography: references.bib

book:
  title: "OptiFert: Evaluation der Digit Soil Technologie"
  author: "ZHAW / Agroscope"
  date: today
  repo-url: https://github.com/ptochosgeorgos/Optifert
  repo-actions: [edit, issue]
#   chapters:
#     - index.qmd
#     - reports/DEMO_25.qmd
#     - reports/Lysimeter.qmd
#     - reports/Field_Campaign.qmd
  chapters:
    - index.qmd
    - reports/vorwort.qmd
    - part: "DEMO"
      chapters:
        - reports/DEMO_25.qmd
        - reports/DEMO_26.qmd
    - part: "Lysimeter"
      chapters:
        - reports/Lysimeter.qmd
    - part: "Praxisversuche"
      chapters:
        - reports/Field_Campaign_25.qmd
        - reports/Field_Campaign_26.qmd
    - part: "ZOFE"
    
format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    toc-title: "Inhaltsverzeichnis"
    number-sections: true
    code-fold: true
    code-summary: "R-Code anzeigen"

execute:
  warning: false
  message: false
