<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.19">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>1&nbsp; Langzeitversuch DEMO – OptiFert: Evaluation der Digit Soil Technologie</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../reports/DEMO_26.html" rel="next">
<link href="../reports/vorwort.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-bf27225e3a48a9273f3daa8f8e829971.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-fd0503e23dce65854c81c5baaade3bdf.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<link href="../site_libs/htmltools-fill-0.5.9/fill.css" rel="stylesheet">
<script src="../site_libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
<script src="../site_libs/plotly-binding-4.12.1/plotly.js"></script>
<script src="../site_libs/typedarray-0.1/typedarray.min.js"></script>
<script src="../site_libs/jquery-3.5.1/jquery.min.js"></script>
<link href="../site_libs/crosstalk-1.2.2/css/crosstalk.min.css" rel="stylesheet">
<script src="../site_libs/crosstalk-1.2.2/js/crosstalk.min.js"></script>
<link href="../site_libs/plotly-htmlwidgets-css-2.25.2/plotly-htmlwidgets.css" rel="stylesheet">
<script src="../site_libs/plotly-main-2.25.2/plotly-latest.min.js"></script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../reports/DEMO_25.html">DEMO</a></li><li class="breadcrumb-item"><a href="../reports/DEMO_25.html"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Langzeitversuch DEMO</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">OptiFert: Evaluation der Digit Soil Technologie</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/ptochosgeorgos/Optifert" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Einleitung und Methodik</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reports/vorwort.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Vorwort: Wissenschaftliche Einordnung und Limitationen enzymatischer Sensordaten</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">DEMO</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reports/DEMO_25.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Langzeitversuch DEMO</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reports/DEMO_26.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Langzeitversuch DEMO</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Lysimeter</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reports/Lysimeter.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Lysimeter-Versuchsanlage</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Praxisversuche</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reports/Field_Campaign_25.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">On-Farm Feldkampagne (Field Campaign)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../reports/Field_Campaign_26.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">On-Farm Feldkampagne (Field Campaign)</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text">ZOFE</span></span>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Inhaltsverzeichnis</h2>
   
  <ul>
  <li><a href="#hintergrund-und-methodik" id="toc-hintergrund-und-methodik" class="nav-link active" data-scroll-target="#hintergrund-und-methodik"><span class="header-section-number">2</span> 1. Hintergrund und Methodik</a></li>
  <li><a href="#explorative-datenanalyse-nmin-pro-verfahren" id="toc-explorative-datenanalyse-nmin-pro-verfahren" class="nav-link" data-scroll-target="#explorative-datenanalyse-nmin-pro-verfahren"><span class="header-section-number">3</span> 2. Explorative Datenanalyse: Nmin pro Verfahren</a></li>
  <li><a href="#sensor-signale-enzymatische-aktivität-eea" id="toc-sensor-signale-enzymatische-aktivität-eea" class="nav-link" data-scroll-target="#sensor-signale-enzymatische-aktivität-eea"><span class="header-section-number">4</span> 3. Sensor-Signale: Enzymatische Aktivität (EEA)</a></li>
  <li><a href="#systemische-kopplung-korrelationsanalyse" id="toc-systemische-kopplung-korrelationsanalyse" class="nav-link" data-scroll-target="#systemische-kopplung-korrelationsanalyse"><span class="header-section-number">5</span> 4. Systemische Kopplung: Korrelationsanalyse</a>
  <ul class="collapse">
  <li><a href="#theoretischer-hintergrund-warum-enzymsignale-korrelieren" id="toc-theoretischer-hintergrund-warum-enzymsignale-korrelieren" class="nav-link" data-scroll-target="#theoretischer-hintergrund-warum-enzymsignale-korrelieren"><span class="header-section-number">5.0.1</span> Theoretischer Hintergrund: Warum Enzymsignale korrelieren</a></li>
  <li><a href="#kopplung-an-mineralischen-stickstoff-n_min-poolgröße-vs.-flussrate" id="toc-kopplung-an-mineralischen-stickstoff-n_min-poolgröße-vs.-flussrate" class="nav-link" data-scroll-target="#kopplung-an-mineralischen-stickstoff-n_min-poolgröße-vs.-flussrate"><span class="header-section-number">5.0.2</span> Kopplung an mineralischen Stickstoff (<span class="math inline">\(N_{min}\)</span>): Poolgröße vs.&nbsp;Flussrate</a></li>
  <li><a href="#schlussfolgerung-und-problem-der-multikollinearität" id="toc-schlussfolgerung-und-problem-der-multikollinearität" class="nav-link" data-scroll-target="#schlussfolgerung-und-problem-der-multikollinearität"><span class="header-section-number">5.0.3</span> Schlussfolgerung und Problem der Multikollinearität</a></li>
  </ul></li>
  <li><a href="#biologisches-profil-und-dimensionsreduktion" id="toc-biologisches-profil-und-dimensionsreduktion" class="nav-link" data-scroll-target="#biologisches-profil-und-dimensionsreduktion"><span class="header-section-number">6</span> 5. Biologisches Profil und Dimensionsreduktion</a>
  <ul class="collapse">
  <li><a href="#warum-robuste-pca-nach-hubert" id="toc-warum-robuste-pca-nach-hubert" class="nav-link" data-scroll-target="#warum-robuste-pca-nach-hubert"><span class="header-section-number">6.0.1</span> Warum robuste PCA nach Hubert?</a></li>
  <li><a href="#herleitung-und-interpretation-der-hauptachsen-human-friendly-names" id="toc-herleitung-und-interpretation-der-hauptachsen-human-friendly-names" class="nav-link" data-scroll-target="#herleitung-und-interpretation-der-hauptachsen-human-friendly-names"><span class="header-section-number">6.0.2</span> Herleitung und Interpretation der Hauptachsen („Human-Friendly Names“)</a></li>
  <li><a href="#visualisierung-im-zweidimensionalen-raum" id="toc-visualisierung-im-zweidimensionalen-raum" class="nav-link" data-scroll-target="#visualisierung-im-zweidimensionalen-raum"><span class="header-section-number">6.0.3</span> Visualisierung im zweidimensionalen Raum</a></li>
  </ul></li>
  <li><a href="#mechanistisches-n-balance-modell-intervall-basiert" id="toc-mechanistisches-n-balance-modell-intervall-basiert" class="nav-link" data-scroll-target="#mechanistisches-n-balance-modell-intervall-basiert"><span class="header-section-number">7</span> 6. Mechanistisches N-Balance Modell (Intervall-basiert)</a>
  <ul class="collapse">
  <li><a href="#die-idee-massenbilanz-als-rahmen" id="toc-die-idee-massenbilanz-als-rahmen" class="nav-link" data-scroll-target="#die-idee-massenbilanz-als-rahmen"><span class="header-section-number">7.1</span> 6.1 Die Idee: Massenbilanz als Rahmen</a>
  <ul class="collapse">
  <li><a href="#methodische-festlegungen-und-randbedingungen" id="toc-methodische-festlegungen-und-randbedingungen" class="nav-link" data-scroll-target="#methodische-festlegungen-und-randbedingungen"><span class="header-section-number">7.1.1</span> Methodische Festlegungen und Randbedingungen:</a></li>
  </ul></li>
  <li><a href="#variablen-und-designmatrix" id="toc-variablen-und-designmatrix" class="nav-link" data-scroll-target="#variablen-und-designmatrix"><span class="header-section-number">7.2</span> 6.2 Variablen und Designmatrix</a></li>
  <li><a href="#voraussetzungen-und-annahmen" id="toc-voraussetzungen-und-annahmen" class="nav-link" data-scroll-target="#voraussetzungen-und-annahmen"><span class="header-section-number">7.3</span> 6.3 Voraussetzungen und Annahmen</a></li>
  <li><a href="#modell-implementierung-in-r" id="toc-modell-implementierung-in-r" class="nav-link" data-scroll-target="#modell-implementierung-in-r"><span class="header-section-number">7.4</span> 6.4 Modell-Implementierung in R</a></li>
  <li><a href="#modell-evaluation-und-visualisierung" id="toc-modell-evaluation-und-visualisierung" class="nav-link" data-scroll-target="#modell-evaluation-und-visualisierung"><span class="header-section-number">7.5</span> 6.5 Modell-Evaluation und Visualisierung</a>
  <ul class="collapse">
  <li><a href="#partielle-residuen-der-isolierte-biologische-effekt-pc2" id="toc-partielle-residuen-der-isolierte-biologische-effekt-pc2" class="nav-link" data-scroll-target="#partielle-residuen-der-isolierte-biologische-effekt-pc2"><span class="header-section-number">7.5.1</span> Partielle Residuen: Der isolierte biologische Effekt (PC2)</a></li>
  <li><a href="#d-visualisierung-der-regressionsebene" id="toc-d-visualisierung-der-regressionsebene" class="nav-link" data-scroll-target="#d-visualisierung-der-regressionsebene"><span class="header-section-number">7.5.2</span> 3D-Visualisierung der Regressionsebene</a></li>
  </ul></li>
  <li><a href="#synthese-und-interpretation-der-felddaten" id="toc-synthese-und-interpretation-der-felddaten" class="nav-link" data-scroll-target="#synthese-und-interpretation-der-felddaten"><span class="header-section-number">7.6</span> 6.6 Synthese und Interpretation der Felddaten</a></li>
  </ul></li>
  <li><a href="#saisonaler-ansatz-erste-vs.-letzte-messung" id="toc-saisonaler-ansatz-erste-vs.-letzte-messung" class="nav-link" data-scroll-target="#saisonaler-ansatz-erste-vs.-letzte-messung"><span class="header-section-number">8</span> 7. Saisonaler Ansatz: Erste vs.&nbsp;Letzte Messung</a></li>
  <li><a href="#pedoclimatic-proxy-lag-analysis-lmm-aic" id="toc-pedoclimatic-proxy-lag-analysis-lmm-aic" class="nav-link" data-scroll-target="#pedoclimatic-proxy-lag-analysis-lmm-aic"><span class="header-section-number">9</span> 8. Pedoclimatic Proxy &amp; Lag Analysis (LMM + AIC)</a>
  <ul class="collapse">
  <li><a href="#vergleich-der-akkumulationsfenster-aic-ranking" id="toc-vergleich-der-akkumulationsfenster-aic-ranking" class="nav-link" data-scroll-target="#vergleich-der-akkumulationsfenster-aic-ranking"><span class="header-section-number">9.1</span> Vergleich der Akkumulationsfenster (AIC-Ranking)</a></li>
  <li><a href="#synthese-der-lag-analyse-kurzfristige-enzympulse-vs.-träger-nmin-pool" id="toc-synthese-der-lag-analyse-kurzfristige-enzympulse-vs.-träger-nmin-pool" class="nav-link" data-scroll-target="#synthese-der-lag-analyse-kurzfristige-enzympulse-vs.-träger-nmin-pool"><span class="header-section-number">9.2</span> Synthese der Lag-Analyse: Kurzfristige Enzympulse vs.&nbsp;träger Nmin-Pool</a></li>
  <li><a href="#visualisierung-einfluss-des-7-tage-niederschlags-auf-die-gesamtaktivität-pc1" id="toc-visualisierung-einfluss-des-7-tage-niederschlags-auf-die-gesamtaktivität-pc1" class="nav-link" data-scroll-target="#visualisierung-einfluss-des-7-tage-niederschlags-auf-die-gesamtaktivität-pc1"><span class="header-section-number">9.3</span> Visualisierung: Einfluss des 7-Tage-Niederschlags auf die Gesamtaktivität (PC1)</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/ptochosgeorgos/Optifert/edit/main/reports/DEMO_25.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/ptochosgeorgos/Optifert/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../reports/DEMO_25.html">DEMO</a></li><li class="breadcrumb-item"><a href="../reports/DEMO_25.html"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Langzeitversuch DEMO</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Langzeitversuch DEMO</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="hintergrund-und-methodik" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> 1. Hintergrund und Methodik</h1>
<p>Der Langzeitversuch DEMO untersucht seit 1989 die Auswirkungen unterschiedlicher organischer und mineralischer Düngungsstrategien auf die Bodenfruchtbarkeit und das Ertragspotenzial.</p>
<p>Die agronomische Fragestellung berücksichtigt, dass die Bestimmung der mineralischen Stickstofffraktionen (Nmin: Ammonium und Nitrat) im Labor eine statische Messung darstellt. In der aktuellen Kampagne (2025) evaluieren wir den Einsatz der Digit Soil Sensoren. Diese messen die enzymatische Aktivität (EEA) direkt im Boden und quantifizieren das Mineralisierungspotenzial der Bodenbiologie.</p>
<p>Die Datenaufbereitung für diese Analyse integriert die räumlichen Replikate (Proben A und B) innerhalb der Parzellen, um die mikrobielle Heterogenität des Bodens abzubilden.</p>
</section>
<section id="explorative-datenanalyse-nmin-pro-verfahren" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> 2. Explorative Datenanalyse: Nmin pro Verfahren</h1>
<p>Der erste analytische Schritt gilt der Etablierung unserer agronomischen Baseline. Die klassische Laboranalyse liefert uns die Konzentrationen von Ammonium (NH4) und Nitrat (NO3).</p>
<p>Wir betrachten die Verteilung dieser Nährstoffe aufgeteilt nach den etablierten Düngungsverfahren. Boxplots sind hierfür das Mittel der Wahl, da sie nicht nur den Median aufzeigen, sondern auch die Streuung und eventuelle Extremwerte (Ausreißer) innerhalb einer Behandlungsgruppe sichtbar machen. Eine hohe Streuung innerhalb eines Verfahrens ist in Feldversuchen oft ein Indikator für räumliche Bodenunterschiede oder ungleichmäßige Mineralisierungsschübe.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="DEMO_25_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="sensor-signale-enzymatische-aktivität-eea" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> 3. Sensor-Signale: Enzymatische Aktivität (EEA)</h1>
<p>Analog zu den Nmin-Werten analysieren wir die Rohsignale der Digit Soil Sensoren. Ursprünglich wurden fünf Enzymaktivitäten erfasst (LAP, NAG, GLS, MUP, MUX). In den Messreihen zeigte sich jedoch, dass das Enzym LAP (Leucin-Aminopeptidase) erhebliche Messausfälle und unvollständige Werte (hoher NA-Anteil) aufweist. Um einen übermässigen Ausschluss valider Probenahmezeitpunkte bei multivariaten Analysen zu vermeiden, konzentriert sich die Auswertung auf die vier verlässlich quantifizierten Enzyme: <strong>NAG, GLS, MUP und MUX</strong>.</p>
<p>Während Nmin das Produkt der Mineralisierung darstellt, messen diese Enzyme die Raten der mikrobiellen Umsetzungsprozesse. NAG spiegelt den Stickstoffkreislauf wider, während GLS für den Kohlenstoffabbau, MUP für den Phosphorkreislauf und MUX für Hemicellulose steht. Die Fragestellung ist: Weisen die Sensordaten eine messbare Sensitivität gegenüber den Düngungsverfahren auf? Gleiche relative Muster in den Boxplots der Enzyme und Nmin-Werte (z.B. erhöhte Werte bei organischen Verfahren wie “MIST”) dokumentieren die Reaktion der Sensorik auf die Behandlungen.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="DEMO_25_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="systemische-kopplung-korrelationsanalyse" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> 4. Systemische Kopplung: Korrelationsanalyse</h1>
<p>Zur Überprüfung der Zusammenhänge der Messvariablen untereinander verwenden wir die Spearman-Rangkorrelation, da enzymatische Reaktionen Sättigungskurven aufweisen können und nicht zwingend linear verlaufen.</p>
<section id="theoretischer-hintergrund-warum-enzymsignale-korrelieren" class="level3" data-number="5.0.1">
<h3 data-number="5.0.1" class="anchored" data-anchor-id="theoretischer-hintergrund-warum-enzymsignale-korrelieren"><span class="header-section-number">5.0.1</span> Theoretischer Hintergrund: Warum Enzymsignale korrelieren</h3>
<p>Biologisch und physikochemisch ist eine enge Kopplung der Enzymsignale im Boden zu erwarten: 1. <strong>Geteilte pedoklimatische Treiber:</strong> Bodenmikroorganismen reagieren simultan auf übergeordnete Umweltfaktoren wie Bodentemperatur, Feuchtegehalt und den Eintrag von labilem Kohlenstoff (z. B. durch Wurzelexsudate). Ein günstiges Milieu stimuliert die Synthese und Sekretion mehrerer Enzymklassen gleichzeitig. 2. <strong>Stabilisierung des abiontischen Enzympools:</strong> Ein bedeutender Anteil der mit der SEAR-Methode gemessenen extrazellulären Enzyme liegt stabilisiert an Tonmineralen und Huminstoffen vor <span class="citation" data-cites="Burns2013 Nannipieri2018">(<a href="#ref-Burns2013" role="doc-biblioref">Burns et al. 2013</a>; <a href="#ref-Nannipieri2018" role="doc-biblioref">Nannipieri et al. 2018</a>)</span>. Dieser abiontische Pool akkumuliert über Wochen bis Monate unter den gleichen Standortbedingungen und puffert kurzfristige Schwankungen ab. 3. <strong>Biochemisch gekoppelte Zyklen:</strong> Der Abbau organischer Substanz erfordert das koordinierte Zusammenspiel von C-, N- und P-spaltenden Hydrolasen.</p>
</section>
<section id="kopplung-an-mineralischen-stickstoff-n_min-poolgröße-vs.-flussrate" class="level3" data-number="5.0.2">
<h3 data-number="5.0.2" class="anchored" data-anchor-id="kopplung-an-mineralischen-stickstoff-n_min-poolgröße-vs.-flussrate"><span class="header-section-number">5.0.2</span> Kopplung an mineralischen Stickstoff (<span class="math inline">\(N_{min}\)</span>): Poolgröße vs.&nbsp;Flussrate</h3>
<p>Besonders aufschlussreich ist die Frage, wie die gemessenen Enzymaktivitäten mit den anorganischen Stickstoffgehalten (<span class="math inline">\(NO_3^-\)</span>, <span class="math inline">\(NH_4^+\)</span>, <span class="math inline">\(N_{min,ges}\)</span>) verknüpft sind. Systemdynamisch betrachtet beschreiben die beiden Messgrößen grundlegend unterschiedliche physikalische Dimensionen:</p>
<ol type="1">
<li><strong>Zustandsvariable vs.&nbsp;Flussrate:</strong> <span class="math inline">\(N_{min}(t)\)</span> ist eine statische <strong>Zustandsgröße</strong> (ein akkumulierter Pool in <span class="math inline">\(kg\,N/ha\)</span>), während die mikrobielle Aktivität bzw. die Enzymsignale (später kondensiert in PC1 und PC2) eine <strong>prozessuale Flussrate</strong> (Mineralisierungsgeschwindigkeit) widerspiegeln.</li>
<li><strong>Dynamische Massenbilanz (DGL-Perspektive):</strong> Formal lässt sich die zeitliche Dynamik des <span class="math inline">\(N_{min}\)</span>-Pools über eine Reaktions-Transport-Differentialgleichung beschreiben: <span class="math display">\[\frac{d N_{min}(t)}{dt} = - f(N_{min}(t), \dots) + m(\text{PC1}, \text{PC2}) \cdot S(t)\]</span> Hierbei stellt der enzymkatalysierte Abbau organischer Substrate <span class="math inline">\(S(t)\)</span> mit der Rate <span class="math inline">\(m\)</span> im einfachsten Fall eine lineare Inhomogenität 1. Ordnung dar. Der Senkenterm <span class="math inline">\(f(N_{min})\)</span> bündelt die pflanzliche Aufnahme, mikrobielle Re-Immobilisierung sowie Auswaschungsverluste (formal oft als Potenzreihe <span class="math inline">\(\sum k_i N_{min}^i\)</span> oder Michaelis-Menten-Kinetik modelliert).</li>
<li><strong>Theoretische Unbestimmtheit des Vorzeichens einer statischen Korrelation:</strong> Der gemessene Pool <span class="math inline">\(N_{min}(t)\)</span> ist das zeitliche Integral über alle vergangenen Zu- und Abflüsse: <span class="math display">\[N_{min}(t) = N_{min}(t_0) + \int_{t_0}^t \left( m(\tau) S(\tau) - f(N_{min}(\tau)) \right) d\tau\]</span>
<ul>
<li>Fällt eine Phase intensiver enzymatischer Aktivität (<span class="math inline">\(m \cdot S\)</span> groß) mit starkem vegetativem Pflanzenwachstum zusammen, dominiert der pflanzliche Entzug die Massenbilanz (<span class="math inline">\(f(N_{min}) \gg m \cdot S\)</span>). Der <span class="math inline">\(N_{min}\)</span>-Pool wird trotz hoher mikrobieller Mineralisierung rasch entleert (<span class="math inline">\(\frac{d N_{min}}{dt} &lt; 0\)</span>). Empirisch resultiert daraus eine <strong>negative Korrelation</strong> (N-Verdünnungseffekt, verwandt mit dem Piper-Steenbjerg-Phänomen).</li>
<li>Bei fehlendem Bewuchs oder niedrigen Senkentermen führt dieselbe Aktivität hingegen zur N-Akkumulation (<strong>positive Korrelation</strong>).</li>
<li>Schließlich kann mikrobieller N-Erwerb (z. B. Hochregulierung von NAG) gezielt unter Bedingungen relativen N-Mangels induziert werden (N-Mining), was ebenfalls eine negative Beziehung erzeugt.</li>
</ul></li>
</ol>
<p>A priori ist das Vorzeichen einer statischen Snapshot-Korrelation <span class="math inline">\(\text{Cor}(N_{min}(t), \text{Enzyme}(t))\)</span> im Feld somit mathematisch und biogeochemisch unbestimmt. Dies liefert die methodische Rechtfertigung, in Kapitel 6 von statischen Momentanwerten zur intervallbasierten Massenbilanz (<span class="math inline">\(\Delta N_{min}\)</span> abzüglich Entzug) überzugehen.</p>
<p>Die folgende Heatmap veranschaulicht diese Zusammenhänge zunächst empirisch für alle gemessenen Enzyme und die anorganischen Stickstofffraktionen:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="DEMO_25_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="schlussfolgerung-und-problem-der-multikollinearität" class="level3" data-number="5.0.3">
<h3 data-number="5.0.3" class="anchored" data-anchor-id="schlussfolgerung-und-problem-der-multikollinearität"><span class="header-section-number">5.0.3</span> Schlussfolgerung und Problem der Multikollinearität</h3>
<p>Die Korrelationsmatrix liefert zwei zentrale Erkenntnisse: 1. <strong>Hohe Interkorrelation der Enzyme (<span class="math inline">\(r = 0.55\text{ bis }0.70\)</span>):</strong> Alle Enzyme korrelieren untereinander stark positiv. Dies ist einerseits ein ermutigender Beleg für ein kohärentes biologisches Signal. Andererseits vermindert eine derart ausgeprägte Kollinearität den Gehalt an unabhängiger Information drastisch. 2. <strong>Negative Assoziation mit Nitrat und <span class="math inline">\(N_{min}\)</span> (<span class="math inline">\(r \approx -0.30\text{ bis }-0.50\)</span>):</strong> Die Enzymaktivitäten korrelieren negativ mit <span class="math inline">\(NO_3^-\)</span> und dem Gesamt-<span class="math inline">\(N_{min}\)</span>. Dies stützt die Beobachtung, dass hohe biologische Aktivitätsphasen im Feld zeitlich mit der Phase des höchsten Stickstoffentzugs der Maispflanzen zusammenfallen.</p>
<p><strong>Konsequenz für die Modellierung:</strong> Würde man alle vier Enzymsignale gleichzeitig als Prädiktoren in ein multiples Regressionsmodell aufnehmen, entstünde extreme <strong>Multikollinearität</strong> (Variance Inflation), was zu instabilen Schätzern, Vorzeichenwechseln und uninterpretierbaren p-Werten führt. Um diese redundante Information verlustarm und mathematisch stabil zu bündeln, ist eine Dimensionsreduktion mittels robuster Hauptkomponentenanalyse (rPCA) der methodisch gebotene Schritt.</p>
</section>
</section>
<section id="biologisches-profil-und-dimensionsreduktion" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> 5. Biologisches Profil und Dimensionsreduktion</h1>
<p>Aufgrund der ausgeprägten Multikollinearität zwischen den Enzymen führen wir eine robuste Hauptkomponentenanalyse (rPCA nach Hubert) durch.</p>
<section id="warum-robuste-pca-nach-hubert" class="level3" data-number="6.0.1">
<h3 data-number="6.0.1" class="anchored" data-anchor-id="warum-robuste-pca-nach-hubert"><span class="header-section-number">6.0.1</span> Warum robuste PCA nach Hubert?</h3>
<p>Biologische Felddaten und fluorogene Messreihen weisen typischerweise asymmetrische Verteilungen und potenzielle Ausreißer auf. Der Algorithmus von Hubert <span class="citation" data-cites="Hubert2005">(<a href="#ref-Hubert2005" role="doc-biblioref">2005</a>)</span> kombiniert Projektionsverfolgung mit robusten MCD-Kovarianzschätzern (<em>Minimum Covariance Determinant</em>). Dadurch wird verhindert, dass extreme Einzelmessungen die Achsenorientierung dominieren. Da die Enzymaktivitäten unterschiedliche absolute Wertebereiche aufweisen, ist eine vorangehende Skalierung (<code>scale = TRUE</code>, z-Standardisierung) zwingend erforderlich.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Eigenvektoren (Loadings) der ersten beiden Hauptkomponenten (erklärte Varianz: PC1 = 71.3 %, PC2 = 28.7 %)</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Enzym</th>
<th style="text-align: right;">PC1 (Ladung)</th>
<th style="text-align: right;">PC2 (Ladung)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">NAG</td>
<td style="text-align: right;">-0.400</td>
<td style="text-align: right;">0.213</td>
</tr>
<tr class="even">
<td style="text-align: left;">GLS</td>
<td style="text-align: right;">-0.380</td>
<td style="text-align: right;">0.840</td>
</tr>
<tr class="odd">
<td style="text-align: left;">MUP</td>
<td style="text-align: right;">-0.811</td>
<td style="text-align: right;">-0.499</td>
</tr>
<tr class="even">
<td style="text-align: left;">MUX</td>
<td style="text-align: right;">-0.193</td>
<td style="text-align: right;">0.000</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="herleitung-und-interpretation-der-hauptachsen-human-friendly-names" class="level3" data-number="6.0.2">
<h3 data-number="6.0.2" class="anchored" data-anchor-id="herleitung-und-interpretation-der-hauptachsen-human-friendly-names"><span class="header-section-number">6.0.2</span> Herleitung und Interpretation der Hauptachsen („Human-Friendly Names“)</h3>
<p>Die beiden ersten Hauptkomponenten fassen zusammen 100 % der im zweidimensionalen Raum abgebildeten robusten Varianz zusammen. Die mathematische Linearkombination der standardisierten Enzymaktivitäten begründet die fachliche Benennung der Achsen:</p>
<p><span class="math display">\[\begin{aligned}
\text{PC1} &amp;= -0.400 \cdot \text{NAG} - 0.380 \cdot \text{GLS} - 0.811 \cdot \text{MUP} - 0.193 \cdot \text{MUX} \\
\text{PC2} &amp;= +0.213 \cdot \text{NAG} + 0.840 \cdot \text{GLS} - 0.499 \cdot \text{MUP} + 0.000 \cdot \text{MUX}
\end{aligned}\]</span></p>
<ol type="1">
<li><strong>PC1 (71.3 % der Varianz) – „Index der biologischen Gesamtaktivität“:</strong> Alle vier Enzymsignale laden mit demselben (negativen) Vorzeichen auf PC1. Wenn die allgemeine mikrobielle Dichte und Aktivität im Boden zunimmt, verändern sich alle Sensorwerte in die gleiche Richtung. Dies entspricht mathematisch dem klassischen „Größenfaktor“ (<em>Size Effect</em>) in der multivariaten Morphometrie. PC1 quantifiziert somit das übergeordnete Aktivitätsniveau des Bodens (stark geprägt durch die saure Phosphatase MUP).</li>
<li><strong>PC2 (28.7 % der Varianz) – „Enzymatischer Shift (C/N- vs.&nbsp;P-Allokation)“:</strong> PC2 stellt eine bipolare Kontrastachse dar: Die Kohlenstoff- und Stickstoff-abbauenden Enzyme GLS (<span class="math inline">\(+0.840\)</span>) und NAG (<span class="math inline">\(+0.213\)</span>) stehen der Phosphatase MUP (<span class="math inline">\(-0.499\)</span>) mit entgegengesetztem Vorzeichen gegenüber. Ein hoher PC2-Wert reflektiert somit eine relative Schwerpunktverlagerung hin zum C- und N-Abbau gegenüber der P-Mineralisierung.</li>
</ol>
</section>
<section id="visualisierung-im-zweidimensionalen-raum" class="level3" data-number="6.0.3">
<h3 data-number="6.0.3" class="anchored" data-anchor-id="visualisierung-im-zweidimensionalen-raum"><span class="header-section-number">6.0.3</span> Visualisierung im zweidimensionalen Raum</h3>
<p>Im folgenden Biplot werden die Beprobungspunkte im Koordinatensystem von PC1 und PC2 dargestellt und nach Düngungsverfahren eingefärbt:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="DEMO_25_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Zur Verdeutlichung der Kopplung mit den mineralischen N-Fraktionen werden dieselben Punkte entlang des PC1/PC2-Raums mit den Nitrat- und Ammoniumkonzentrationen eingefärbt:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="DEMO_25_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="mechanistisches-n-balance-modell-intervall-basiert" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> 6. Mechanistisches N-Balance Modell (Intervall-basiert)</h1>
<p>Die explorative Datenanalyse zeigt Varianzen auf Ebene der Replikate. Zur Quantifizierung des biologischen Beitrags zur Stickstoffmineralisierung verwenden wir ein lineares gemischtes Modell (Linear Mixed-Effects Model, LMM) für die Longitudinaldaten.</p>
<section id="die-idee-massenbilanz-als-rahmen" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="die-idee-massenbilanz-als-rahmen"><span class="header-section-number">7.1</span> 6.1 Die Idee: Massenbilanz als Rahmen</h2>
<p>Das statistische Modell basiert auf der physikalischen Massenbilanz für jedes Beprobungsintervall (<span class="math inline">\(t_1 \rightarrow t_2\)</span>). Die zeitliche Veränderung des mineralischen Stickstoffpools im Bodenprofil (<span class="math inline">\(\Delta N_{min}\)</span>) ist das Resultat aus Zuflüssen (Mineralisation, Düngung) und Abflüssen (Pflanzenentzug, gasförmige und Auswaschungsverluste):</p>
<p><span class="math display">\[\Delta N_{min} = N_{min}(t_2) - N_{min}(t_1) = N_{\text{mineralisiert}} + N_{\text{gedüngt}} - N_{\text{entzug}} - N_{\text{verlust}}\]</span></p>
<p>Um die durch mikrobielle Prozesse aus der organischen Bodensubstanz freigesetzte Netto-Stickstoffmenge (<span class="math inline">\(dN\)</span> in <span class="math inline">\(kg\,N/ha\)</span>) als Zielgröße zu isolieren, wird die Gleichung umgestellt:</p>
<p><span class="math display">\[dN \equiv N_{\text{mineralisiert}} - N_{\text{verlust}} = \Delta N_{min} \cdot 4.5 + N_{\text{entzug}} - N_{\text{gedüngt}}\]</span></p>
<section id="methodische-festlegungen-und-randbedingungen" class="level3" data-number="7.1.1">
<h3 data-number="7.1.1" class="anchored" data-anchor-id="methodische-festlegungen-und-randbedingungen"><span class="header-section-number">7.1.1</span> Methodische Festlegungen und Randbedingungen:</h3>
<ol type="1">
<li><strong>Vorzeichen des Pflanzenentzugs:</strong> Der pflanzliche Stickstoffentzug (<span class="math inline">\(N_{\text{entzug}}\)</span>) wird zur gemessenen Pooländerung <span class="math inline">\(\Delta N_{min}\)</span> <strong>addiert</strong> (und nicht subtrahiert): Der von den Maispflanzen im Intervall aufgenommene Stickstoff musste zuvor durch mikrobielle Mineralisation (oder Restdünger) bereitgestellt werden, um dem Bodenprofil entzogen werden zu können. Eine Parzelle mit hohem Entzug weist folglich eine hohe N-Bereitstellungsleistung auf.</li>
<li><strong>Behandlung der Düngeevents:</strong> Die Düngung liegt im vorliegenden Datensatz als jährliche Gesamtsumme pro Parzelle vor. Da eine zeitlich hochaufgelöste Fraktionierung der Düngetermine auf die einzelnen Intervalle derzeit nicht ohne spekulative Modellannahmen möglich ist, wird <span class="math inline">\(N_{\text{gedüngt}}\)</span> nicht im Intervall abgezogen. Die verfahrensspezifischen N-Niveaus (z. B. Mist, Gülle, NPK) werden stattdessen primär über das hierarchische Random-Intercept-Design (<code>(1 | ParzNrFeld)</code>) auf Parzellenebene kontrolliert.</li>
<li><strong>Konsequenz des LAP-Ausschlusses:</strong> Leucin-Aminopeptidase (LAP) ist das zentrale Enzym für die primäre Spaltung von Peptidbindungen (Proteolyse) und damit für die direkte Freisetzung niedermolekularer N-Verbindungen. Da LAP wegen hoher Messausfälle verworfen werden musste, fehlt dem Enzym-Set der direkte Proteinsensor. Der N-Umsatz wird stattdessen über NAG (Chitinabbau), die mikrobielle Gesamtaktivität (PC1, dominiert von Phosphatase MUP) sowie den relativen C/N- zu P-Shift (PC2) approximiert.</li>
</ol>
<p>Die resultierende Zielgröße <span class="math inline">\(dN\)</span> wird durch die Enzym-Hauptkomponenten und den Niederschlag (inkl. quadratischem Term für nicht-lineare Auswaschungsverluste) modelliert:</p>
<p><span class="math display">\[dN \sim PC1 + PC2 + Precip + Precip^2 + (1 | ParzNrFeld)\]</span></p>
</section>
</section>
<section id="variablen-und-designmatrix" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="variablen-und-designmatrix"><span class="header-section-number">7.2</span> 6.2 Variablen und Designmatrix</h2>
<p>Das Modell (<code>lmer</code>) verwendet folgende Struktur:</p>
<ul>
<li><strong>Abhängige Variable (<span class="math inline">\(Y\)</span>):</strong> <code>dN</code> (<span class="math inline">\(kg/ha\)</span>) – Die aus der Massenbilanz rekonstruierte Netto-Mineralisation im Intervall (<span class="math inline">\(\Delta N_{min} \cdot 4.5 + N_{Entzug}\)</span>).</li>
<li><strong>Fixed Effects:</strong>
<ul>
<li><code>PC1</code>: Index der biologischen Gesamtaktivität (alle Ladungen negativ).</li>
<li><code>PC2</code>: Enzymatischer Shift (C/N- vs.&nbsp;P-Allokation).</li>
<li><code>Cum_Precip_mm</code>: Kumulierte Niederschlagssumme zwischen <span class="math inline">\(t_1\)</span> und <span class="math inline">\(t_2\)</span> (Open-Meteo API) als Proxy für Auswaschungsverluste.</li>
</ul></li>
<li><strong>Random Effects:</strong>
<ul>
<li><code>(1 | ParzNrFeld)</code>: Random Intercept für jede Parzelle zur Korrektur der individuellen Basislinie und des standortspezifischen Dünungsniveaus.</li>
</ul></li>
</ul>
</section>
<section id="voraussetzungen-und-annahmen" class="level2" data-number="7.3">
<h2 data-number="7.3" class="anchored" data-anchor-id="voraussetzungen-und-annahmen"><span class="header-section-number">7.3</span> 6.3 Voraussetzungen und Annahmen</h2>
<p>Für die Modellierung gelten folgende Annahmen: 1. <strong>Konvertierungsfaktor:</strong> Die Umrechnung von <span class="math inline">\(mg/kg\)</span> in <span class="math inline">\(kg/ha\)</span> erfolgt mit dem Faktor 4.5 (Annahme: 30 cm Tiefe, Lagerungsdichte <span class="math inline">\(1.5 \ g/cm^3\)</span>). 2. <strong>Ertrags-Baseline (Mais):</strong> Für das Jahr 2025 wurde der historische durchschnittliche Gesamtstickstoffentzug (<code>Total_N_Entzug_kg_ha</code>) der jeweiligen Parzelle exklusiv für die Kultur <em>Mais</em> (<code>Kultur == "MA"</code>) berechnet. 3. <strong>Logistischer Pflanzenentzug (S-Kurve):</strong> Der Stickstoffentzug wird mechanistisch über eine logistische Wachstumsfunktion (S-Kurve) basierend auf kumulierten Wachstumsgradtagen (GDD, Basis <span class="math inline">\(6^\circ C\)</span>) modelliert <span class="citation" data-cites="archontoulisNonlinearRegressionModels2015 overmanMathematicalModelsCrop2002">(<a href="#ref-archontoulisNonlinearRegressionModels2015" role="doc-biblioref">Archontoulis and Miguez 2015</a>; <a href="#ref-overmanMathematicalModelsCrop2002" role="doc-biblioref">Overman and Scholtz III 2002</a>)</span>: <span class="math display">\[ N_{up}(GDD) = \frac{N_{max}}{1 + \exp(-0.012 \cdot (GDD - 750))} \]</span> Die Parameter sind: * <span class="math inline">\(N_{max} =\)</span> Historischer Mais-Entzug der Parzelle * Wachstumsrate (<span class="math inline">\(r\)</span>) <span class="math inline">\(= 0.012\)</span> * Wendepunkt (<span class="math inline">\(GDD_{inf}\)</span>) <span class="math inline">\(= 750 \ GDD\)</span> (entspricht ca. BBCH 51, dem Zeitpunkt der maximalen täglichen N-Aufnahme bei Mais <span class="citation" data-cites="benderNutrientUptakePartitioning2013">(<a href="#ref-benderNutrientUptakePartitioning2013" role="doc-biblioref">Bender et al. 2013</a>)</span>). Der berechnete Netto-Entzug im Intervall <span class="math inline">\(t_1 \rightarrow t_2\)</span> wird zu <span class="math inline">\(\Delta N_{min}\)</span> addiert. 4. <strong>Zeitliche Integration:</strong> Die Enzymmessung zum Zeitpunkt <span class="math inline">\(t_2\)</span> repräsentiert das Intervall <span class="math inline">\(t_1 \rightarrow t_2\)</span>.</p>
</section>
<section id="modell-implementierung-in-r" class="level2" data-number="7.4">
<h2 data-number="7.4" class="anchored" data-anchor-id="modell-implementierung-in-r"><span class="header-section-number">7.4</span> 6.4 Modell-Implementierung in R</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula: dN ~ PC1 + PC2 + Cum_Precip_mm + I(Cum_Precip_mm^2) + (1 | ParzNrFeld)
   Data: df_model

REML criterion at convergence: 842.5

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-1.4662 -0.5483 -0.2010  0.3274  3.0889 

Random effects:
 Groups     Name        Variance Std.Dev.
 ParzNrFeld (Intercept)  639.2   25.28   
 Residual               2549.9   50.50   
Number of obs: 79, groups:  ParzNrFeld, 10

Fixed effects:
                     Estimate Std. Error         df t value Pr(&gt;|t|)    
(Intercept)        377.670661  77.279099  71.529190   4.887 6.06e-06 ***
PC1                 17.593646   6.876147  73.999187   2.559  0.01255 *  
PC2                -11.689297  10.489098  73.874814  -1.114  0.26871    
Cum_Precip_mm       -6.337523   1.533616  70.340115  -4.132 9.76e-05 ***
I(Cum_Precip_mm^2)   0.027406   0.006768  70.550001   4.049  0.00013 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Correlation of Fixed Effects:
            (Intr) PC1    PC2    Cm_Pr_
PC1          0.616                     
PC2          0.341  0.566              
Cum_Prcp_mm -0.980 -0.649 -0.317       
I(Cm_Pr_^2)  0.959  0.674  0.293 -0.995
fit warnings:
Some predictor variables are on very different scales: consider rescaling. 
You may also use (g)lmerControl(autoscale = TRUE) to improve numerical stability.</code></pre>
</div>
</div>
<p>Wie in Kapitel 5 hergeleitet und anhand der Ladungen quantifiziert, repräsentiert PC1 das übergeordnete Aktivitätsniveau (Index der biol. Gesamtaktivität, alle Ladungen negativ) und PC2 die stöchiometrische Verschiebung zwischen Kohlenstoff-/Stickstoff-Erwerb (GLS, NAG positiv) und Phosphormobilisierung (MUP negativ).</p>
<p>Daraus wird folgende Hypothese für das N-Balance Modell abgeleitet: Eine erhöhte relative Aktivität kohlenstoffabbauender Enzyme (hoher PC2-Wert) führt durch mikrobielle Immobilisierung zu einer Reduktion des verfügbaren Stickstoffs.</p>
<p>Die Modellergebnisse für die physikalisch korrigierte Zielvariable <span class="math inline">\(dN\)</span> zeigen: * <strong>PC1 (allgemeine biologische Aktivität):</strong> Weist einen signifikanten Koeffizienten auf (17.59 kg N/ha pro Index-Einheit, p = 0.013). Da alle Enzymladungen auf PC1 negativ definiert sind, ist dieser Effekt im Kontext der saisonalen Dynamik (Peak des Pflanzenentzugs im Hochsommer bei moderaten Sensorwerten vs.&nbsp;hohe Spätsommer-Enzymaktivität bei Abreife) zu interpretieren. * <strong>PC2 (Enzymatischer Shift):</strong> Weist einen Koeffizienten von -11.69 kg N/ha auf (p = 0.269), was die Hypothese einer leichten Reduktion des verfügbaren N bei relativem C-Überschuss stützt, wenngleich der Effekt statistisch nicht die Signifikanzschwelle erreicht. * <strong>Niederschlag (Auswaschungsverluste):</strong> Zeigt den physikalisch plausiblen negativen linearen Effekt (-6.34 kg N/ha pro mm Niederschlag, p &lt; 0.001) mit einer hochsignifikanten quadratischen Krümmung (0.0274, p &lt; 0.001), was den überproportionalen Auswaschungsverlust bei Starkregenereignissen präzise abbildet.</p>
<p>Die Modellgüte bestätigt die Plausibilität der korrigierten Massenbilanz: Das Modell erklärt marginal (nur durch Fixed Effects) 25.2% der Varianz (<span class="math inline">\(R^2_m = 0.252\)</span>) und konditional (inklusive Parzellen-Baselines) 40.2% der Varianz (<span class="math inline">\(R^2_c = 0.402\)</span>). Der durchschnittliche Vorhersagefehler (RMSE) beträgt 46.9 kg N/ha.</p>
</section>
<section id="modell-evaluation-und-visualisierung" class="level2" data-number="7.5">
<h2 data-number="7.5" class="anchored" data-anchor-id="modell-evaluation-und-visualisierung"><span class="header-section-number">7.5</span> 6.5 Modell-Evaluation und Visualisierung</h2>
<p>Um den biologischen Effekt zu isolieren und visuell greifbar zu machen, betrachten wir das Modell in zwei Dimensionen (Partielle Residuen) und in drei Dimensionen (Regressionsebene).</p>
<section id="partielle-residuen-der-isolierte-biologische-effekt-pc2" class="level3" data-number="7.5.1">
<h3 data-number="7.5.1" class="anchored" data-anchor-id="partielle-residuen-der-isolierte-biologische-effekt-pc2"><span class="header-section-number">7.5.1</span> Partielle Residuen: Der isolierte biologische Effekt (PC2)</h3>
<p>Da der Niederschlag die Varianz von <span class="math inline">\(dN\)</span> stark dominiert, berechnen wir die partiellen Residuen. Dabei wird der mathematische Effekt von Niederschlag und allgemeiner Aktivität (PC1) herausgerechnet, um isoliert die Beziehung zwischen dem C/N-Enzymshift (PC2) und der verbleibenden Stickstoffdynamik darzustellen.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="DEMO_25_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="d-visualisierung-der-regressionsebene" class="level3" data-number="7.5.2">
<h3 data-number="7.5.2" class="anchored" data-anchor-id="d-visualisierung-der-regressionsebene"><span class="header-section-number">7.5.2</span> 3D-Visualisierung der Regressionsebene</h3>
<p>Das Modell definiert eine Ebene im dreidimensionalen Raum, aufgespannt durch den biologischen Shift (PC2) und den physikalischen Verlust (Niederschlag). Die interaktive Grafik erlaubt es, die Modellfläche und die Beobachtungen räumlich zu explorieren.</p>
<div class="cell">
<div class="cell-output-display">
<div class="plotly html-widget html-fill-item" id="htmlwidget-255b138c4b2cf27ea720" style="width:100%;height:464px;"></div>
<script type="application/json" data-for="htmlwidget-255b138c4b2cf27ea720">{"x":{"visdat":{"1a2c3ba89de4":["function () ","plotlyVisDat"],"1a2c18568f60":["function () ","data"]},"cur_data":"1a2c18568f60","attrs":{"1a2c18568f60":{"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"x":{},"y":{},"z":{},"type":"scatter3d","mode":"markers","marker":{"size":4,"color":"#2980b9","opacity":0.80000000000000004},"name":"Beobachtungen","inherit":true},"1a2c18568f60.1":{"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"z":{},"type":"surface","x":{},"y":{},"opacity":0.59999999999999998,"colorscale":"Viridis","name":"Modell-Ebene","inherit":true}},"layout":{"margin":{"b":40,"l":60,"t":25,"r":10},"scene":{"xaxis":{"title":"PC2 (C/N Shift)"},"yaxis":{"title":"Niederschlag (mm)"},"zaxis":{"title":"dN (kg N/ha)"}},"title":"3D Modell-Ebene: Stickstoff-Massenbilanz","hovermode":"closest","showlegend":false,"legend":{"yanchor":"top","y":0.5}},"source":"A","config":{"modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"data":[{"x":[0.30982263728865395,-0.17616328970673203,0.1070408878160804,1.2449980169270369,-0.80714406029896046,-0.89931303919934191,-0.82767830216438065,2.192790997018716,-0.13460631493250877,0.23519981327851339,0.028420732009168809,0.83763063267898941,0.18090979442232602,0.12547921439440279,-0.17493457593554756,0.67136479594760889,-0.32957681724567173,-0.086664636569886072,0.40689635333439184,0.26837910626698819,-1.1731165373916708,-0.11599572325498059,0.80262704132986151,1.6348755485449025,0.89396692059670624,0.18377586758884384,3.9552573808729035,0.79865547139033632,-0.53077800779479689,0.14832421345396093,1.8352278712140198,0.14037881307400754,-0.88158325313804098,0.35251119463827851,0.53645680007503949,-0.32941195491910008,0.44629933345609951,0.51096710020700686,1.1928043961924519,0.52959557147803515,0.35724340396081844,-0.10814445260188642,-0.18598543234523313,0.036358965400267486,-0.68262441189798895,0.61083323228323594,0.58713165468205153,0.33511177949670917,-0.48147289854625569,0.53648762543693851,-0.072458681480260342,0.72161890647165083,0.36500405540341285,0.26007567392401076,0.34407788345512624,0.86927020416964784,-0.033758001616826218,0.65530281212136032,1.3492720801578202,0.19227635115213404,-1.0888462103738559,1.3045870325407229,1.4507419153568355,0.5604855474843764,-0.41271284412807918,-0.69097908443247313,0.73918278820471228,0.10584824023269239,0.046442117305714813,0.3037399312436872,1.6037151901290503,-0.39189190815156838,-0.42322456761347432,-0.77461143792052778,0.94174509924286187,-0.019729042862437967,-1.1887598989759658,-0.65294784001080652,0.62129060937166869],"y":[130.59999999999999,64.299999999999997,162.40000000000001,173.40000000000001,130.59999999999999,64.299999999999997,162.40000000000001,173.40000000000001,130.59999999999999,64.299999999999997,162.40000000000001,173.40000000000001,130.59999999999999,64.299999999999997,162.40000000000001,130.59999999999999,64.299999999999997,162.40000000000001,173.40000000000001,130.59999999999999,64.299999999999997,162.40000000000001,173.40000000000001,130.59999999999999,64.299999999999997,162.40000000000001,173.40000000000001,130.59999999999999,64.299999999999997,162.40000000000001,173.40000000000001,130.59999999999999,64.299999999999997,162.40000000000001,173.40000000000001,130.59999999999999,64.299999999999997,162.40000000000001,173.40000000000001,130.59999999999999,64.299999999999997,162.40000000000001,173.40000000000001,130.59999999999999,64.299999999999997,162.40000000000001,173.40000000000001,130.59999999999999,64.299999999999997,162.40000000000001,173.40000000000001,130.59999999999999,64.299999999999997,162.40000000000001,173.40000000000001,130.59999999999999,64.299999999999997,162.40000000000001,173.40000000000001,130.59999999999999,64.299999999999997,162.40000000000001,173.40000000000001,130.59999999999999,64.299999999999997,162.40000000000001,173.40000000000001,130.59999999999999,64.299999999999997,162.40000000000001,173.40000000000001,130.59999999999999,64.299999999999997,162.40000000000001,173.40000000000001,130.59999999999999,64.299999999999997,162.40000000000001,173.40000000000001],"z":[-0.31101158576426813,86.12931289953228,138.20223654809368,6.742989249458633,-2.0660115857642678,88.919312899532287,135.36723654809367,9.1279892494586328,-1.5149495023436392,41.346314646620129,34.605811910991754,2.5209602971295979,-1.5149495023436392,42.381314646620126,35.280811910991758,-2.6138642715147555,59.147470344101258,51.414966479412314,2.0872691010346918,-4.5038642715147574,60.182470344101262,47.724966479412316,3.4822691010346913,5.5981612731176078,93.259855034349911,74.150754246030999,-22.88790825823628,1.0981612731176069,86.374855034349906,59.210754246030994,-0.61290825823627859,-4.3090158890938444,88.000513105622886,69.945850008664578,3.4115811229982604,-3.4990158890938461,97.945513105622894,60.180850008664578,2.6465811229982608,-3.6803805822090347,74.955368395827563,116.08980958473845,5.9056512084840698,1.8546194177909641,73.335368395827558,116.80980958473845,6.7606512084840702,-1.8154125887655281,123.90529899531047,183.58129605469779,4.6574820061843525,-4.4254125887655285,116.52529899531046,186.1012960546978,11.137482006184353,9.2368092692597354,144.89481874940782,221.3288693431094,2.0720607647606784,5.8618092692597337,149.66481874940783,214.44386934310938,8.1920607647606776,5.6352548487011322,118.52567640872051,190.26960171889485,7.8332947681568088,2.9802548487011316,119.60567640872051,186.84960171889486,12.603294768156809,-3.087992847428823,45.108794420366308,37.074378068304938,-0.083375586996532025,-4.0779928474288223,44.20879442036631,35.679378068304935,1.6266244130034684],"type":"scatter3d","mode":"markers","marker":{"color":"#2980b9","size":4,"opacity":0.80000000000000004,"line":{"color":"rgba(31,119,180,1)"}},"name":"Beobachtungen","error_y":{"color":"rgba(31,119,180,1)"},"error_x":{"color":"rgba(31,119,180,1)"},"line":{"color":"rgba(31,119,180,1)"},"frame":null},{"colorbar":{"title":"dN<br />z_matrix","ticklen":2,"len":0.5,"lenmode":"fraction","y":1,"yanchor":"top"},"colorscale":"Viridis","showscale":true,"z":[[97.371459743363559,82.121518537936623,68.678793560825682,57.043284812030862,47.21499229155225,39.193915999389588,32.980055935543021,28.573412100012547,25.973984492798252,25.181773113899965,26.196777963317686,29.018999041051586,33.648436347101608,40.085089881467695,48.328959644149677,58.380045635147781,70.238347854462404,83.903866302092752,99.376600978039164,116.65655188230164],[94.206725883510202,78.956784678083267,65.514059700972325,53.878550952177505,44.050258431698893,36.029182139536232,29.815322075689664,25.40867824015919,22.809250632944895,22.017039254046608,23.03204410346433,25.85426518119823,30.483702487248252,36.920356021614339,45.164225784296377,55.215311775294481,67.073613994608991,80.739132442239338,96.211867118185751,113.49181802244823],[91.041992023656789,75.792050818229853,62.349325841118912,50.713817092324092,40.88552457184548,32.864448279682819,26.650588215836251,22.243944380305777,19.644516773091482,18.852305394193195,19.867310243610916,22.689531321344816,27.318968627394838,33.755622161760925,41.999491924442964,52.050577915441067,63.908880134755577,77.574398582385925,93.047133258332337,110.32708416259482],[87.877258163803432,72.627316958376497,59.184591981265555,47.549083232470736,37.720790711992123,29.699714419829462,23.485854355982895,19.07921052045242,16.479782913238125,15.687571534339838,16.70257638375756,19.52479746149146,24.154234767541482,30.590888301907569,38.834758064589664,48.885844055587768,60.744146274902164,74.409664722532511,89.882399398478924,107.1623503027414],[84.712524303950019,69.462583098523083,56.019858121412142,44.384349372617322,34.55605685213871,26.534980559976049,20.321120496129481,15.914476660599007,13.315049053384712,12.522837674486425,13.537842523904146,16.360063601638046,20.989500907688068,27.426154442054155,35.670024204736251,45.721110195734354,57.579412415048751,71.244930862679098,86.717665538625511,103.99761644288799],[81.547790444096663,66.297849238669727,52.855124261558785,41.219615512763966,31.391322992285353,23.370246700122692,17.156386636276125,12.749742800745651,10.150315193531355,9.3581038146330684,10.37310866405079,13.19532974178469,17.824767047834712,24.261420582200799,32.505290344882837,42.556376335880941,54.414678555195451,68.080197002825798,83.552931678772211,100.83288258303469],[78.383056584243249,63.133115378816314,49.690390401705372,38.054881652910552,28.22658913243194,20.205512840269279,13.991652776422711,9.5850089408922372,6.985581333677942,6.193369954779655,7.2083748041973763,10.030595881931276,14.660033187981298,21.096686722347386,29.340556485029424,39.391642476027528,51.249944695342037,64.915463142972385,80.388197818918798,97.668148723181275],[75.218322724389893,59.968381518962957,46.525656541852015,34.890147793057196,25.061855272578583,17.040778980415922,10.826918916569355,6.4202750810388807,3.8208474738245854,3.0286360949262985,4.0436409443440198,6.8658620220779198,11.495299328127942,17.931952862494029,26.175822625176011,36.226908616174114,48.085210835488738,61.750729283119085,77.223463959065498,94.503414863327976],[72.053588864536479,56.803647659109544,43.360922681998602,31.725413933203782,21.89712141272517,13.876045120562509,7.6621850567159413,3.2555412211854673,0.65611361397117207,-0.13609776492711489,0.87890708449060639,3.7011281622245065,8.3305654682745285,14.767219002640559,23.011088765322597,33.062174756320701,44.920476975635324,58.585995423265672,74.058730099212084,91.338681003474562],[68.888855004683123,53.638913799256187,40.196188822145245,28.560680073350426,18.732387552871813,10.711311260709152,4.4974511968625848,0.090807361332110759,-2.5086202458821845,-3.3008316247804714,-2.2858267753627501,0.53639430237114993,5.1658316084211719,11.602485142787259,19.846354905469298,29.897440896467401,41.755743115781911,55.421261563412259,70.893996239358671,88.173947143621149],[65.724121144829709,50.474179939402774,37.031454962291832,25.395946213497012,15.5676536930184,7.5465774008557389,1.3327173370091714,-3.0739264985213026,-5.6733541057355978,-6.4655654846338848,-5.4505606352161635,-2.6283395574822634,2.0010977485677586,8.4377512829338457,16.681621045615884,26.732707036613988,38.591009255928498,52.256527703558845,67.729262379505258,85.009213283767735],[62.559387284976353,47.309446079549417,33.866721102438476,22.231212353643656,12.402919833165043,4.3818435410023824,-1.8320165228441851,-6.2386603583746592,-8.8380879655889544,-9.6302993444872413,-8.6152944950695201,-5.79307341733562,-1.163636111285598,5.273017423080546,13.516887185762585,23.567973176760688,35.426275396075084,49.091793843705432,64.564528519651844,81.844479423914322],[59.394653425122939,44.144712219696004,30.701987242585062,19.066478493790243,9.2381859733116301,1.217109681148969,-4.9967503826975985,-9.4033942182280725,-12.002821825442368,-12.795033204340655,-11.780028354922933,-8.9578072771890334,-4.3283699711390113,2.1082835632271326,10.352153325909171,20.403239316907275,32.261541536221671,45.927059983852018,61.399794659798431,78.679745564060909],[56.229919565269583,40.979978359842647,27.537253382731706,15.901744633936886,6.0734521134582735,-1.9476241787043875,-8.1614842425509551,-12.568128078081429,-15.167555685295724,-15.959767064194011,-14.94476221477629,-12.12254113704239,-7.4931038309923679,-1.0564502966262808,7.1874194660557578,17.238505457053861,29.096807676368371,42.762326123998719,58.235060799945131,75.515011704207609],[53.06518570541617,37.815244499989234,24.372519522878292,12.737010774083473,2.9087182536048601,-5.1123580385578009,-11.326218102404368,-15.732861937934842,-18.332289545149138,-19.124500924047425,-18.109496074629703,-15.287274996895803,-10.657837690845781,-4.2211841564796941,4.0226856062023444,14.073771597200448,25.932073816514958,39.597592264145305,55.070326940091718,72.350277844354196],[49.900451845562813,34.650510640135877,21.207785663024936,9.5722769142301161,-0.2560156062484964,-8.2770918984111574,-14.490951962257725,-18.897595797788199,-21.497023405002494,-22.289234783900781,-21.27422993448306,-18.45200885674916,-13.822571550699138,-7.3859180163331075,0.85795174634893101,10.909037737347035,22.767339956661658,36.432858404292006,51.905593080238418,69.185543984500896],[46.7357179857094,31.485776780282464,18.043051803171522,6.4075430543767027,-3.4207494661019098,-11.441825758264571,-17.655685822111138,-22.062329657641612,-24.661757264855908,-25.453968643754195,-24.438963794336473,-21.616742716602573,-16.987305410552551,-10.550651876186521,-2.3067821135044824,7.7443038774936213,19.602606096808245,33.268124544438592,48.740859220385005,66.020810124647483],[43.570984125856043,28.321042920429107,14.878317943318166,3.2428091945233462,-6.5854833259552663,-14.606559618117927,-20.820419681964495,-25.227063517494969,-27.826491124709264,-28.618702503607551,-27.60369765418983,-24.78147657645593,-20.152039270405908,-13.715385736039821,-5.4715159733577821,4.5795700176403216,16.437872236954831,30.103390684585179,45.576125360531591,62.856076264794069],[40.40625026600263,25.156309060575694,11.713584083464752,0.078075334669932772,-9.7502171858086797,-17.771293477971341,-23.985153541817908,-28.391797377348382,-30.991224984562677,-31.783436363460964,-30.768431514043243,-27.946210436309343,-23.316773130259321,-16.880119595893234,-8.6362498332111954,1.4148361577869082,13.273138377101418,26.938656824731765,42.411391500678178,59.691342404940656],[37.241516406149273,21.991575200722338,8.5488502236113959,-3.0866585251834238,-12.914951045662036,-20.936027337824697,-27.149887401671265,-31.556531237201739,-34.155958844416034,-34.948170223314321,-33.9331653738966,-31.1109442961627,-26.481506990112621,-20.044853455746534,-11.800983693064495,-1.7498977020663915,10.108404517248005,23.773922964878352,39.246657640824765,56.526608545087242]],"type":"surface","x":[-1.1887598989759658,-0.91802214740497268,-0.64728439583397956,-0.37654664426298645,-0.10580889269199334,0.16492885887899966,0.43566661044999289,0.70640436202098611,0.97714211359197911,1.2478798651629721,1.5186176167339651,1.7893553683049586,2.0600931198759516,2.3308308714469446,2.601568623017938,2.8723063745889306,3.143044126159924,3.4137818777309175,3.68451962930191,3.9552573808729035],"y":[64.299999999999997,70.042105263157893,75.784210526315789,81.526315789473685,87.268421052631581,93.010526315789477,98.752631578947359,104.49473684210525,110.23684210526315,115.97894736842105,121.72105263157894,127.46315789473684,133.20526315789473,138.94736842105263,144.68947368421053,150.43157894736842,156.17368421052632,161.91578947368421,167.65789473684211,173.40000000000001],"opacity":0.59999999999999998,"name":"Modell-Ebene","frame":null}],"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
</div>
</div>
</section>
</section>
<section id="synthese-und-interpretation-der-felddaten" class="level2" data-number="7.6">
<h2 data-number="7.6" class="anchored" data-anchor-id="synthese-und-interpretation-der-felddaten"><span class="header-section-number">7.6</span> 6.6 Synthese und Interpretation der Felddaten</h2>
<p>Die Modellierung der Netto-Stickstoffveränderung (<span class="math inline">\(dN\)</span>) über die gemessenen Sommerintervalle liefert ein klares phänomenologisches Bild. Im bereinigten Datensatz, in dem die Messintervalle zeitlich korrekt abgeglichen wurden, verliert das enzymatische Profil (die Hauptkomponenten PC1 und PC2) seine statistische Signifikanz als linearer Prädiktor. Stattdessen wird die Varianz der Stickstoffmassenbilanz im Feld signifikant und stark nicht-linear durch den kumulierten Niederschlag dominiert (<span class="math inline">\(p &lt; 0.001\)</span>).</p>
<p>Die beobachteten Netto-Mineralisierungsraten verhalten sich im Wesentlichen wie ein physikalisches System, in dem moderate Niederschläge vom Boden gepuffert werden, während Extremereignisse zu einem quadratisch ansteigenden Auswaschungsverlust führen. Ein robustes biologisches Signal, welches auf eine enzymatische Steuerung der Netto-Mineralisierung im Makromaßstab hindeutet, lässt sich aus den vorliegenden Daten nicht sicher extrahieren.</p>
<p>Das Ausbleiben messbarer Korrelationen zwischen den in-vitro Enzymaktivitäten und den in-situ Stickstoffflüssen lässt verschiedene Interpretationen zu:</p>
<ol type="1">
<li><p><strong>Hypothese 1: Dominanz makroskopischer Flüsse</strong> Es ist davon auszugehen, dass die schiere Masse des durch starken Sommerniederschlag verlagerten Stickstoffs (Auswaschung, Denitrifikation) so groß ist, dass sie jeglichen mikrobiologischen Netto-Beitrag überlagert. Das biologische Signal fungiert unter diesen Witterungsbedingungen lediglich als Rauschen innerhalb der dominanten physikalischen Massenbilanz.</p></li>
<li><p><strong>Hypothese 2: Diskrepanz zwischen potenzieller und realer Aktivität</strong> Die Reaktionsplatten messen die enzymatische <em>Potenzialaktivität</em> unter laboroptimierten Bedingungen (Substratsättigung, optimale Pufferung). Im Feld sind diese Enzyme jedoch Limitationen durch Diffusion, Trockenheit und fehlende Substratverfügbarkeit unterworfen. Das Laborpotenzial lässt sich folglich nicht zwingend als reale Umsetzungsrate in die Feldskala übersetzen.</p></li>
<li><p><strong>Hypothese 3: Technische Varianz und Sensorrauschen</strong> Letztlich muss in Betracht gezogen werden, dass die in-situ Heterogenität des Bodens und methodische Varianzen des Assays (z.B. Transportbedingungen, Matrixeffekte) eine zu geringe methodische Wiederholbarkeit aufweisen. Ohne hinreichende Konsistenz misst die Methode primär stochastisches Rauschen, welches prinzipbedingt keine Korrelation zu den realen Nährstoffflüssen aufbauen kann.</p></li>
</ol>
</section>
</section>
<section id="saisonaler-ansatz-erste-vs.-letzte-messung" class="level1" data-number="8">
<h1 data-number="8"><span class="header-section-number">8</span> 7. Saisonaler Ansatz: Erste vs.&nbsp;Letzte Messung</h1>
<p>Als alternativen Ansatz zur Intervall-basierten Modellierung betrachten wir nun ausschließlich die Nettoveränderung über die gesamte Vegetationsperiode. Hierbei verwenden wir lediglich die erste und die letzte Messung jeder Parzelle.</p>
<p>Die Fragestellung lautet: Kann die saisonale Veränderung der Enzymaktivität (<span class="math inline">\(\\Delta\)</span>PC1 und <span class="math inline">\(\\Delta\)</span>PC2) die saisonale Stickstoff-Nettoveränderung (<span class="math inline">\(dN\)</span>) erklären, wenn wir die Varianz durch Witterung ausschließen? Da der Niederschlag über die gesamte Saison für alle Parzellen im Versuch identisch ist, fungiert er im Querschnitt dieses Modells lediglich als Konstante und fällt somit als erklärende Variable weg. Die Enzymdynamik rückt dadurch völlig in den Fokus.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula: dN_season ~ Delta_PC1 + Delta_PC2 + (1 | ParzNrFeld)
   Data: df_season

REML criterion at convergence: 150.7

Scaled residuals: 
     Min       1Q   Median       3Q      Max 
-1.17035 -0.54094 -0.00745  0.55532  1.15927 

Random effects:
 Groups     Name        Variance  Std.Dev.
 ParzNrFeld (Intercept) 11405.859 106.798 
 Residual                   1.919   1.385 
Number of obs: 20, groups:  ParzNrFeld, 10

Fixed effects:
            Estimate Std. Error       df t value Pr(&gt;|t|)    
(Intercept) 197.5627    33.8019   9.0297   5.845 0.000242 ***
Delta_PC1    -0.1212     0.2973   8.0027  -0.408 0.694312    
Delta_PC2     2.4962     0.8884   8.0082   2.810 0.022831 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Correlation of Fixed Effects:
          (Intr) Dl_PC1
Delta_PC1  0.030       
Delta_PC2 -0.028 -0.030</code></pre>
</div>
</div>
<p>Die Modellergebnisse der saisonalen Massenbilanz offenbaren ein differenziertes Bild: * <strong><span class="math inline">\(\Delta\)</span>PC1 (Veränderung der Gesamtaktivität):</strong> Zeigt keinen statistisch signifikanten Zusammenhang mit der saisonalen Stickstoffbereitstellung (-0.12 kg N/ha, p = 0.694). * <strong><span class="math inline">\(\Delta\)</span>PC2 (Saisonaler Enzymatischer Shift):</strong> Weist einen statistisch signifikanten positiven Effekt auf (2.5 kg N/ha pro Einheit, p = 0.023).</p>
<p>Parzellen, bei denen sich das mikrobielle Enzymprofil im Verlauf der Vegetationsperiode stärker in Richtung Kohlenstoff- und Stickstoff-abbauender Hydrolasen (GLS, NAG) verschob, stellten über die gesamte Saison hinweg signifikant mehr mineralisierten Stickstoff für den Pflanzenentzug bereit.</p>
<p>Wir visualisieren diesen Zusammenhang über die gesamte Saison:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="DEMO_25_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Dies liefert eine wichtige methodische Erkenntnis: Während in kurzzeitigen 4-Wochen-Intervallen stochastische Witterungsextreme (Starkregen und Auswaschung) das biologische Signal überdecken, tritt bei Betrachtung des saisonalen Großintervalls – in dem die Witterung für alle Parzellen des Standorts als gemeinsame Konstante wirkt – eine signifikante Kopplung zwischen dem funktionellen Enzymshift (<span class="math inline">\(\Delta\)</span>PC2) und der langfristigen Stickstoffnachlieferung hervor.</p>
</section>
<section id="pedoclimatic-proxy-lag-analysis-lmm-aic" class="level1" data-number="9">
<h1 data-number="9"><span class="header-section-number">9</span> 8. Pedoclimatic Proxy &amp; Lag Analysis (LMM + AIC)</h1>
<p>Bodenenzyme sind zu einem wesentlichen Teil an Organo-Mineral-Komplexe stabilisiert und bilden ein biochemisches „Reservoir“, welches pedoklimatische Umweltfaktoren (Niederschlag, Temperatur) über längere Zeiträume integriert <span class="citation" data-cites="Burns2013 Wallenstein2008">(<a href="#ref-Burns2013" role="doc-biblioref">Burns et al. 2013</a>; <a href="#ref-Wallenstein2008" role="doc-biblioref">Wallenstein and Weintraub 2008</a>)</span>. Daher lassen sich enzymatische Abundanzen und Aktivitätsmuster häufig besser durch kumulative Witterungsfenster (z. B. 7-, 14- oder 30-Tage-Aggregate) als durch punktuelle Tagesmessungen erklären.</p>
<p>Da unsere Enzym- und Nmin-Messungen zeitlich diskret (T1 bis T5) und nicht kontinuierlich vorliegen, nutzen wir Linear Mixed Models (LMM) in Kombination mit dem Akaike-Informationskriterium (AIC), um empirisch zu bestimmen, welches Akkumulationsfenster die Varianz der Sensordaten und N-Fraktionen am besten erklärt.</p>
<section id="vergleich-der-akkumulationsfenster-aic-ranking" class="level2" data-number="9.1">
<h2 data-number="9.1" class="anchored" data-anchor-id="vergleich-der-akkumulationsfenster-aic-ranking"><span class="header-section-number">9.1</span> Vergleich der Akkumulationsfenster (AIC-Ranking)</h2>
<p>Wir modellieren die einzelnen Enzymsignale (NAG, GLS, MUP, MUX), die beiden Hauptkomponenten (PC1, PC2) sowie den gesamten mineralischen Stickstoff (<code>Nmin_Total</code>) als Funktion des kumulativen Niederschlags und der Wärmesumme (GDD), mit Parzellen-spezifischem Random Intercept (<code>(1 | ParzNrFeld)</code>):</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>AIC-Modellvergleich für enzymatische Signale und Nmin über verschiedene pedoklimatische Akkumulationsfenster (DEMO 2025)</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Signal</th>
<th style="text-align: right;">7-Tage</th>
<th style="text-align: right;">14-Tage</th>
<th style="text-align: right;">30-Tage</th>
<th style="text-align: right;">Aridity (14d)</th>
<th style="text-align: left;">Best_Lag</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">NAG</td>
<td style="text-align: right;">459.1</td>
<td style="text-align: right;">494.7</td>
<td style="text-align: right;">478.0</td>
<td style="text-align: right;">496.3</td>
<td style="text-align: left;">7-Tage</td>
</tr>
<tr class="even">
<td style="text-align: left;">GLS</td>
<td style="text-align: right;">607.1</td>
<td style="text-align: right;">678.5</td>
<td style="text-align: right;">641.0</td>
<td style="text-align: right;">687.7</td>
<td style="text-align: left;">7-Tage</td>
</tr>
<tr class="odd">
<td style="text-align: left;">MUP</td>
<td style="text-align: right;">801.2</td>
<td style="text-align: right;">843.0</td>
<td style="text-align: right;">813.7</td>
<td style="text-align: right;">852.8</td>
<td style="text-align: left;">7-Tage</td>
</tr>
<tr class="even">
<td style="text-align: left;">MUX</td>
<td style="text-align: right;">387.4</td>
<td style="text-align: right;">582.4</td>
<td style="text-align: right;">532.7</td>
<td style="text-align: right;">587.2</td>
<td style="text-align: left;">7-Tage</td>
</tr>
<tr class="odd">
<td style="text-align: left;">PC1</td>
<td style="text-align: right;">284.5</td>
<td style="text-align: right;">365.5</td>
<td style="text-align: right;">325.7</td>
<td style="text-align: right;">374.9</td>
<td style="text-align: left;">7-Tage</td>
</tr>
<tr class="even">
<td style="text-align: left;">PC2</td>
<td style="text-align: right;">194.2</td>
<td style="text-align: right;">229.7</td>
<td style="text-align: right;">209.9</td>
<td style="text-align: right;">232.8</td>
<td style="text-align: left;">7-Tage</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Nmin_Total</td>
<td style="text-align: right;">291.3</td>
<td style="text-align: right;">285.6</td>
<td style="text-align: right;">271.9</td>
<td style="text-align: right;">305.3</td>
<td style="text-align: left;">30-Tage</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="synthese-der-lag-analyse-kurzfristige-enzympulse-vs.-träger-nmin-pool" class="level2" data-number="9.2">
<h2 data-number="9.2" class="anchored" data-anchor-id="synthese-der-lag-analyse-kurzfristige-enzympulse-vs.-träger-nmin-pool"><span class="header-section-number">9.2</span> Synthese der Lag-Analyse: Kurzfristige Enzympulse vs.&nbsp;träger Nmin-Pool</h2>
<p>Die Modellergebnisse zeigen ein bemerkenswert klares, biogeochemisch plausibles Muster:</p>
<ol type="1">
<li><strong>Enzymsignale und Hauptkomponenten (7-Tage-Optimum):</strong>
<ul>
<li>Sämtliche Einzelsensoren (NAG, GLS, MUP, MUX) sowie beide Hauptkomponenten (PC1 und PC2) weisen ihr eindeutiges AIC-Minimum beim <strong>7-Tage-Fenster</strong> auf.</li>
<li>Dies belegt, dass die extrazelluläre Enzymaktivität im DEMO-Versuch besonders dynamisch auf kurzfristige, einwöchige Witterungsimpulse (Niederschlagsereignisse und Temperaturspitzen) reagiert.</li>
</ul></li>
<li><strong>Mineralischer Stickstoffpool (<span class="math inline">\(N_{min}\)</span>, 30-Tage-Optimum):</strong>
<ul>
<li>Im Gegensatz zu den Enzymen wird der <span class="math inline">\(N_{min}\)</span>-Gehalt am besten durch das <strong>30-Tage-Fenster</strong> erklärt (<span class="math inline">\(\text{AIC} = 272.1\)</span>).</li>
<li>Der anorganische Stickstoffpool fungiert folglich als trägere Zustandsgröße, die über einen mehrwöchigen Horizont von Mineralisation, kontinuierlicher Pflanzenaufnahme und physikalischen Verlagerungen integriert.</li>
</ul></li>
</ol>
</section>
<section id="visualisierung-einfluss-des-7-tage-niederschlags-auf-die-gesamtaktivität-pc1" class="level2" data-number="9.3">
<h2 data-number="9.3" class="anchored" data-anchor-id="visualisierung-einfluss-des-7-tage-niederschlags-auf-die-gesamtaktivität-pc1"><span class="header-section-number">9.3</span> Visualisierung: Einfluss des 7-Tage-Niederschlags auf die Gesamtaktivität (PC1)</h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="DEMO_25_files/figure-html/plot-pedoclimatic-pc1-1.png" class="img-fluid figure-img" width="864"></p>
</figure>
</div>
</div>
</div>


<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-archontoulisNonlinearRegressionModels2015" class="csl-entry" role="listitem">
Archontoulis, Sotirios V., and Fernando E. Miguez. 2015. <span>“Nonlinear <span>Regression Models</span> and <span>Applications</span> in <span>Agricultural Research</span>.”</span> <em>Agronomy Journal</em> 107 (2): 786–98. <a href="https://doi.org/10.2134/agronj2012.0506">https://doi.org/10.2134/agronj2012.0506</a>.
</div>
<div id="ref-benderNutrientUptakePartitioning2013" class="csl-entry" role="listitem">
Bender, Ross R., Jason W. Haegele, Matias L. Ruffo, and Fred E. Below. 2013. <span>“Nutrient <span>Uptake</span>, <span>Partitioning</span>, and <span>Remobilization</span> in <span>Modern</span>, <span>Transgenic Insect-Protected Maize Hybrids</span>.”</span> <em>Agronomy Journal</em> 105 (1): 161–70. <a href="https://doi.org/10.2134/agronj2012.0352">https://doi.org/10.2134/agronj2012.0352</a>.
</div>
<div id="ref-Burns2013" class="csl-entry" role="listitem">
Burns, Richard G., Jared L. DeForest, Jürgen Marxsen, et al. 2013. <span>“Soil Enzymes in a Changing Environment: Current Knowledge and Future Directions.”</span> <em>Soil Biology and Biochemistry</em> 58: 216–34.
</div>
<div id="ref-Hubert2005" class="csl-entry" role="listitem">
Hubert, Mia, Peter J. Rousseeuw, and Karlien Vanden Branden. 2005. <span>“ROBPCA: A New Approach to Robust Principal Component Analysis.”</span> <em>Technometrics</em> 47 (1): 64–79.
</div>
<div id="ref-Nannipieri2018" class="csl-entry" role="listitem">
Nannipieri, Paolo, Carmen Trasar-Cepeda, and Richard P. Dick. 2018. <span>“Soil Enzyme Activity: A Brief History and Biochemistry as a Basis for Appropriate Interpretations and Meta-Analysis.”</span> <em>Biology and Fertility of Soils</em> 54 (1): 11–19.
</div>
<div id="ref-overmanMathematicalModelsCrop2002" class="csl-entry" role="listitem">
Overman, Allen R., and Richard V. Scholtz III. 2002. <em>Mathematical Models of Crop Growth and Yield</em>. CRC Press.
</div>
<div id="ref-Wallenstein2008" class="csl-entry" role="listitem">
Wallenstein, Matthew D., and Michael N. Weintraub. 2008. <span>“Emerging Tools for Measuring and Modeling the in Situ Activity of Soil Extracellular Enzymes.”</span> <em>Soil Biology and Biochemistry</em> 40 (9): 2098–106.
</div>
</div>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../reports/vorwort.html" class="pagination-link" aria-label="Vorwort: Wissenschaftliche Einordnung und Limitationen enzymatischer Sensordaten">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Vorwort: Wissenschaftliche Einordnung und Limitationen enzymatischer Sensordaten</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../reports/DEMO_26.html" class="pagination-link" aria-label="Langzeitversuch DEMO">
        <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Langzeitversuch DEMO</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/ptochosgeorgos/Optifert/edit/main/reports/DEMO_25.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/ptochosgeorgos/Optifert/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div></div></footer></body></html>