{
  "hash": "da48ac91d46f7cc341e2518421979475",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Langzeitversuch DEMO\"\nformat: html\nexecute:\n  echo: false\n  warning: false\n  message: false\n---\n\n\n::: {.cell}\n\n:::\n\n\n# 1. Hintergrund und Methodik\n\nDer Langzeitversuch DEMO untersucht seit 1989 die Auswirkungen unterschiedlicher organischer und mineralischer Düngungsstrategien auf die Bodenfruchtbarkeit und das Ertragspotenzial.\n\nDie agronomische Fragestellung berücksichtigt, dass die Bestimmung der mineralischen Stickstofffraktionen (Nmin: Ammonium und Nitrat) im Labor eine statische Messung darstellt. In der aktuellen Kampagne (2025) evaluieren wir den Einsatz der Digit Soil Sensoren. Diese messen die enzymatische Aktivität (EEA) direkt im Boden und quantifizieren das Mineralisierungspotenzial der Bodenbiologie.\n\nDie Datenaufbereitung für diese Analyse integriert die räumlichen Replikate (Proben A und B) innerhalb der Parzellen, um die mikrobielle Heterogenität des Bodens abzubilden.\n\n# 2. Explorative Datenanalyse: Nmin pro Verfahren\n\nDer erste analytische Schritt gilt der Etablierung unserer agronomischen Baseline. Die klassische Laboranalyse liefert uns die Konzentrationen von Ammonium (NH4) und Nitrat (NO3).\n\nWir betrachten die Verteilung dieser Nährstoffe aufgeteilt nach den etablierten Düngungsverfahren. Boxplots sind hierfür das Mittel der Wahl, da sie nicht nur den Median aufzeigen, sondern auch die Streuung und eventuelle Extremwerte (Ausreißer) innerhalb einer Behandlungsgruppe sichtbar machen. Eine hohe Streuung innerhalb eines Verfahrens ist in Feldversuchen oft ein Indikator für räumliche Bodenunterschiede oder ungleichmäßige Mineralisierungsschübe.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](DEMO_files/figure-html/unnamed-chunk-1-1.png){width=672}\n:::\n:::\n\n\n# 3. Sensor-Signale: Enzymatische Aktivität (EEA)\n\nAnalog zu den Nmin-Werten analysieren wir die Rohsignale der fünf Digit Soil Sensoren (LAP, NAG, GLS, MUP, MUX).\n\nWährend Nmin das Produkt der Mineralisierung darstellt, messen diese Enzyme die Raten der Umsetzungsprozesse. LAP und NAG spiegeln den Stickstoffkreislauf wider, während GLS für den Kohlenstoffabbau steht. Die Fragestellung ist: Weisen die Sensordaten eine messbare Sensitivität gegenüber den Düngungsverfahren auf? Gleiche relative Muster in den Boxplots der Enzyme und Nmin-Werte (z.B. erhöhte Werte bei organischen Verfahren wie \"MIST\") dokumentieren die Reaktion der Sensorik auf die Behandlungen.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](DEMO_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\n# 4. Systemische Kopplung: Korrelationsanalyse\n\nZur Überprüfung der Zusammenhänge der Variablen untereinander verwenden wir die Spearman-Rangkorrelation, da enzymatische Reaktionen Sättigungskurven aufweisen können und nicht zwingend linear verlaufen.\n\nIn der folgenden Heatmap werden zwei Muster analysiert:\n\n1. Multikollinearität der Enzyme: Eine positive Korrelation der Enzyme untereinander wird erwartet, da die Stoffkreisläufe (C, N, P) im Boden gekoppelt ablaufen.\n\n2. Kopplung an Nmin: Eine Korrelation zwischen den N-spezifischen Enzymen (NAG/LAP) und den Nmin-Laborwerten (NH4/NO3) zeigt an, inwiefern der Sensor das Nachlieferungsvermögen des Bodens abbildet.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](DEMO_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n\n# 5. Biologisches Profil und Dimensionsreduktion\n\nAufgrund der Interkorrelationen zwischen den fünf Enzymen führen wir eine Hauptkomponentenanalyse (rPCA nach Hubert) durch, um die Dimensionalität der Daten zu reduzieren.\n\nDieser Algorithmus ist unempfindlich gegenüber Ausreißern. Die PCA identifiziert als unüberwachtes Verfahren die stärksten Varianzmuster ohne Vorwissen über die Düngungsverfahren.\n\nDie erste Hauptkomponente (PC1) bündelt die gemeinsame Varianz der Sensoren und quantifiziert die biologische Aktivität. Ein starker Overlap der Ellipsen in der Visualisierung zeigt, dass die räumliche Bodenheterogenität den Treatment-Effekt der Düngung überlagert.\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](DEMO_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](DEMO_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n# 6. Mechanistisches N-Balance Modell (Intervall-basiert)\n\nDie explorative Datenanalyse zeigt Varianzen auf Ebene der Replikate. Zur Quantifizierung des biologischen Beitrags zur Stickstoffmineralisierung verwenden wir ein lineares gemischtes Modell (Linear Mixed-Effects Model, LMM) für die Longitudinaldaten.\n\n## 6.1 Die Idee: Massenbilanz als Rahmen\n\nDas statistische Modell basiert auf der physikalischen Massenbilanz. Für die Intervalle ($t_1 \\rightarrow t_2$) wird die Änderung im mineralisierten Stickstoff in kg/ha berechnet ($dN$). Hierzu wird die Konzentration ($mg/kg$) mit einem Standardfaktor (z.B. 4.5 für 0-30 cm Bodentiefe bei Lagerungsdichte 1.5) in $kg/ha$ konvertiert. \n\nDer pflanzliche Entzug (`Interval_N_Entzug_kg_ha`) wird direkt von der $\\Delta N_{min}$ subtrahiert, anstatt als eigener Fixed Effect im Modell geschätzt zu werden. Die resultierende abhängige Variable $dN$ wird dann durch die Enzym-Hauptkomponenten und den Niederschlag (inkl. quadratischem Term für nicht-lineare Auswaschung) erklärt:\n\n$$dN \\sim PC1 + PC2 + Precip + Precip^2$$\n\n## 6.2 Variablen und Designmatrix\n\nDas Modell (`lmer`) verwendet folgende Struktur:\n\n*   **Abhängige Variable ($Y$):** `dN` ($kg/ha$) - Die bereinigte Nettoveränderung des mineralischen Stickstoffs im Boden ($\\Delta N_{min} \\times 4.5 - N_{Entzug}$).\n*   **Fixed Effects:**\n    *   `PC1`: Index der biologischen Gesamtaktivität.\n    *   `PC2`: Enzymatischer Shift (zweite Hauptkomponente).\n    *   `Cum_Precip_mm`: Kumulierte Niederschlagssumme zwischen $t_1$ und $t_2$ (Open-Meteo API) als Proxy für Auswaschungsverluste.\n*   **Random Effects:**\n    *   `(1 | ParzNrFeld)`: Random Intercept für jede Parzelle zur Korrektur der individuellen Basislinie.\n\n## 6.3 Voraussetzungen und Annahmen\n\nFür die Modellierung gelten folgende Annahmen:\n1.  **Konvertierungsfaktor:** Die Umrechnung von $mg/kg$ in $kg/ha$ erfolgt mit dem Faktor 4.5 (Annahme: 30 cm Tiefe, $1.5 \\ g/cm^3$).\n2.  **Ertrags-Baseline (Mais):** Für das Jahr 2025 wurde der historische durchschnittliche Gesamtstickstoffentzug (`Total_N_Entzug_kg_ha`) der jeweiligen Parzelle exklusiv für die Kultur *Mais* (`Kultur == \"MA\"`) berechnet.\n3.  **Logistischer Pflanzenentzug (S-Kurve):** Der Stickstoffentzug wird nicht linear, sondern mechanistisch über eine logistische Wachstumsfunktion (S-Kurve) basierend auf kumulierten Wachstumsgradtagen (GDD, Basis $10^\\circ C$) modelliert [@archontoulisNonlinearRegressionModels2015; @overmanMathematicalModelsCrop2002]:\n    $$ N_{up}(GDD) = \\frac{N_{max}}{1 + \\exp(-0.012 \\cdot (GDD - 750))} $$\n    Die Parameter sind:\n    *   $N_{max} =$ Historischer Mais-Entzug der Parzelle\n    *   Wachstumsrate ($r$) $= 0.012$\n    *   Wendepunkt ($GDD_{inf}$) $= 750 \\ GDD$ (entspricht ca. BBCH 51, dem Zeitpunkt der maximalen täglichen N-Aufnahme bei Mais [@benderNutrientUptakePartitioning2013]).\n    Der berechnete Netto-Entzug im Intervall $t_1 \\rightarrow t_2$ wird dann direkt von $\\Delta N_{min}$ abgezogen.\n4.  **Zeitliche Integration:** Die Enzymmessung zum Zeitpunkt $t_2$ repräsentiert das Intervall $t_1 \\rightarrow t_2$.\n\n## 6.4 Modell-Implementierung in R\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear mixed model fit by REML. t-tests use Satterthwaite's method [\nlmerModLmerTest]\nFormula: dN ~ PC1 + PC2 + Cum_Precip_mm + I(Cum_Precip_mm^2) + (1 | ParzNrFeld)\n   Data: df_model\n\nREML criterion at convergence: 532.7\n\nScaled residuals: \n     Min       1Q   Median       3Q      Max \n-2.50367 -0.43462 -0.01447  0.44291  1.89461 \n\nRandom effects:\n Groups     Name        Variance Std.Dev.\n ParzNrFeld (Intercept)  91.63    9.573  \n Residual               383.76   19.590  \nNumber of obs: 60, groups:  ParzNrFeld, 10\n\nFixed effects:\n                     Estimate Std. Error         df t value Pr(>|t|)    \n(Intercept)        -2.589e+02  3.241e+01  5.185e+01  -7.988 1.36e-10 ***\nPC1                 8.499e-01  2.130e+00  5.497e+01   0.399    0.691    \nPC2                -5.547e+00  3.436e+00  5.371e+01  -1.614    0.112    \nCum_Precip_mm       5.672e+00  6.414e-01  5.021e+01   8.843 8.21e-12 ***\nI(Cum_Precip_mm^2) -2.826e-02  2.861e-03  5.002e+01  -9.879 2.40e-13 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nCorrelation of Fixed Effects:\n            (Intr) PC1    PC2    Cm_Pr_\nPC1          0.238                     \nPC2          0.404  0.018              \nCum_Prcp_mm -0.981 -0.251 -0.352       \nI(Cm_Pr_^2)  0.961  0.271  0.325 -0.995\nfit warnings:\nSome predictor variables are on very different scales: consider rescaling. \nYou may also use (g)lmerControl(autoscale = TRUE) to improve numerical stability.\n```\n\n\n:::\n:::\n\n\nDie PCA-Ladungen definieren die Hauptkomponenten wie folgt: PC1 weist gleichgerichtete, negative Ladungen für NAG, GLS, MUP und MUX auf und quantifiziert die allgemeine enzymatische Aktivität. PC2 weist eine positive Ladung für GLS (Kohlenstoffzyklus) und negative Ladungen für NAG und MUP (Stickstoff- und Phosphorzyklus) auf. PC2 quantifiziert die Verschiebung des enzymatischen Profils zwischen Kohlenstoff- und Nährstoffumsatz.\n\nDaraus wird folgende Hypothese für das N-Balance Modell abgeleitet: Eine erhöhte relative Aktivität kohlenstoffabbauender Enzyme (hoher PC2-Wert) führt durch mikrobielle Immobilisierung zu einer Reduktion des verfügbaren Stickstoffs.\n\nDie Modellergebnisse für die Variable $dN$ zeigen:\nPC1 (allgemeine Aktivität) weist keinen signifikanten Effekt auf die Nettoveränderung auf (0.85 kg N/ha pro Index-Einheit, p = 0.691). \nPC2 weist einen nicht-signifikanten Koeffizienten auf (-5.55 kg N/ha, p = 0.112). Im bereinigten Sommer-Datensatz ist der isolierte enzymatische Effekt linear nicht dominant.\nDer Niederschlag zeigt einen starken nicht-linearen (quadratischen) Effekt. Die linearen und quadratischen Terme (5.67 bzw. -0.0283) quantifizieren den überproportionalen Auswaschungsverlust bei extremen Niederschlägen.\n\nDie Modellperformance ist hoch: Das Modell erklärt marginal (nur durch Fixed Effects) 74.9% der Varianz ($R^2_m = 0.749$) und konditional (inklusive Parzellen-Baselines) 79.7% der Varianz ($R^2_c = 0.797$). Der durchschnittliche Vorhersagefehler (RMSE) beträgt 17.87 kg N/ha.\n\n## 6.5 Modell-Evaluation und Visualisierung\n\nUm den biologischen Effekt zu isolieren und visuell greifbar zu machen, betrachten wir das Modell in zwei Dimensionen (Partielle Residuen) und in drei Dimensionen (Regressionsebene).\n\n### Partielle Residuen: Der isolierte biologische Effekt (PC2)\n\nDa der Niederschlag die Varianz von $dN$ stark dominiert, berechnen wir die partiellen Residuen. Dabei wird der mathematische Effekt von Niederschlag und allgemeiner Aktivität (PC1) herausgerechnet, um isoliert die Beziehung zwischen dem C/N-Enzymshift (PC2) und der verbleibenden Stickstoffdynamik darzustellen.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](DEMO_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n### 3D-Visualisierung der Regressionsebene\n\nDas Modell definiert eine Ebene im dreidimensionalen Raum, aufgespannt durch den biologischen Shift (PC2) und den physikalischen Verlust (Niederschlag). Die interaktive Grafik erlaubt es, die Modellfläche und die Beobachtungen räumlich zu explorieren.\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"plotly html-widget html-fill-item\" id=\"htmlwidget-e3ac9cc211cdf7e223bc\" style=\"width:100%;height:464px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-e3ac9cc211cdf7e223bc\">{\"x\":{\"visdat\":{\"22a52176ba6c21\":[\"function () \",\"plotlyVisDat\"],\"22a5211c63aa55\":[\"function () \",\"data\"]},\"cur_data\":\"22a5211c63aa55\",\"attrs\":{\"22a5211c63aa55\":{\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"x\":{},\"y\":{},\"z\":{},\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"size\":4,\"color\":\"#2980b9\",\"opacity\":0.80000000000000004},\"name\":\"Beobachtungen\",\"inherit\":true},\"22a5211c63aa55.1\":{\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"z\":{},\"type\":\"surface\",\"x\":{},\"y\":{},\"opacity\":0.59999999999999998,\"colorscale\":\"Viridis\",\"name\":\"Modell-Ebene\",\"inherit\":true}},\"layout\":{\"margin\":{\"b\":40,\"l\":60,\"t\":25,\"r\":10},\"scene\":{\"xaxis\":{\"title\":\"PC2 (C/N Shift)\"},\"yaxis\":{\"title\":\"Niederschlag (mm)\"},\"zaxis\":{\"title\":\"dN (kg N/ha)\"}},\"title\":\"3D Modell-Ebene: Stickstoff-Massenbilanz\",\"hovermode\":\"closest\",\"showlegend\":false,\"legend\":{\"yanchor\":\"top\",\"y\":0.5}},\"source\":\"A\",\"config\":{\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"data\":[{\"x\":[0.067762378226258954,0.33271908252366345,-0.21450767232928894,-1.8259849238544013,0.37459124256587234,0.40978068489282915,0.79443754124978783,0.13560672293070913,1.0930368818746066,-0.24413579370376401,0.2417379725165561,0.49333759486257256,1.1316641827343936,0.05224728336564103,-0.85958450681141729,2.1970159270353431,0.13725017994511718,-0.17636681264169779,0.16396593225689318,-1.095714301136999,0.29562155070020585,-0.37756128253565091,0.46575734222103959,-0.65092525019689851,-1.0961522192503526,-1.287832325329378,-0.70076147534077238,0.48992267914093962,-0.67722869243415396,-0.62499351426928218,-0.21676979603684857,-0.11878230643535642,-0.79085894246733945,-1.4046802970136192,0.33784822317721919,-1.3965030454435305,-2.480144546381263,-1.6027397954516001,-0.84315175945736132,-1.2947616079008013,0.33278522447595127,-1.4286956773679444,-1.3547752862772755,-1.6344707184048295,0.14415543468349287,-0.9752076922853905,-1.5449623834502513,0.2707176761056489,-0.27134257907402509,0.46297971716157871,0.18833426746242474,0.9073956775775166,1.7663883769387188,-1.3035995034784793,0.14988689677243811,-1.4882834275467551,0.11214124815913405,0.65527612711790939,-0.12902546878253665,-0.05963179455937323],\"y\":[130.59999999999999,130.59999999999999,130.59999999999999,130.59999999999999,130.59999999999999,130.59999999999999,130.59999999999999,130.59999999999999,130.59999999999999,130.59999999999999,130.59999999999999,130.59999999999999,130.59999999999999,130.59999999999999,130.59999999999999,130.59999999999999,130.59999999999999,130.59999999999999,130.59999999999999,130.59999999999999,64.299999999999997,64.299999999999997,64.299999999999997,64.299999999999997,64.299999999999997,64.299999999999997,64.299999999999997,64.299999999999997,64.299999999999997,64.299999999999997,64.299999999999997,64.299999999999997,64.299999999999997,64.299999999999997,64.299999999999997,64.299999999999997,64.299999999999997,64.299999999999997,64.299999999999997,64.299999999999997,162.40000000000001,162.40000000000001,162.40000000000001,162.40000000000001,162.40000000000001,162.40000000000001,162.40000000000001,162.40000000000001,162.40000000000001,162.40000000000001,162.40000000000001,162.40000000000001,162.40000000000001,162.40000000000001,162.40000000000001,162.40000000000001,162.40000000000001,162.40000000000001,162.40000000000001,162.40000000000001],\"z\":[-2.0076806576066488,-3.2955529743225784,-4.4620535516519855,-2.8036809248511245,-4.3123832895887277,4.663468445861942,4.6079394762768766,-2.0076806576066488,0.17949087274069814,-5.2720535516519842,-1.0486809248511251,-5.4205811800741452,8.0384684458619429,-4.57301921443901,-5.1855529743225786,4.6794908727406996,1.2226167104112704,-2.8105811800741458,1.9529394762768744,-3.5830192144390103,1.6218020378989415,1.8817928389486678,-7.1660040921520931,-8.7860040921520941,-5.405239742769,-14.961961185837371,-4.2704524086472961,-7.8039831103000914,-8.8514827617741325,-5.2631979621010574,-12.785239742769001,-10.815579286403281,-13.881961185837371,-5.1704524086472956,-6.7689831103000913,-7.8164827617741324,-8.0632071610513325,-9.7222046030965554,-6.9322046030965563,-6.0455792864032762,-75.020638750806683,-70.768259100065933,-90.230069307568925,-77.192058758654554,-127.32853745916657,-35.256328120420832,-36.651328120420835,-37.389529744469463,-36.714529744469459,-60.080638750806678,-87.395069307568932,-145.15303105693815,-152.03803105693817,-123.90853745916657,-48.1898799710224,-51.879879971022405,-80.533259100065933,-76.472058758654555,-120.7655720817919,-118.24557208179191],\"type\":\"scatter3d\",\"mode\":\"markers\",\"marker\":{\"color\":\"#2980b9\",\"size\":4,\"opacity\":0.80000000000000004,\"line\":{\"color\":\"rgba(31,119,180,1)\"}},\"name\":\"Beobachtungen\",\"error_y\":{\"color\":\"rgba(31,119,180,1)\"},\"error_x\":{\"color\":\"rgba(31,119,180,1)\"},\"line\":{\"color\":\"rgba(31,119,180,1)\"},\"frame\":null},{\"colorbar\":{\"title\":\"dN<br />z_matrix\",\"ticklen\":2,\"len\":0.5,\"lenmode\":\"fraction\",\"y\":1,\"yanchor\":\"top\"},\"colorscale\":\"Viridis\",\"showscale\":true,\"z\":[[2.739141057637724,12.503007448559458,20.75993795338988,27.509932572129003,32.752991304776799,36.489114151333268,38.718301111798439,39.44055218617217,38.655867374454715,36.364246676645791,32.56569009274574,27.260197622754163,20.447769266671457,12.128405024497283,2.3021048962318673,-9.0311311181249039,-21.871303018572917,-36.218410805112285,-52.072454477743008,-69.433434036464973],[1.373686170279214,11.137552561200948,19.39448306603137,26.144477684770493,31.387536417418289,35.123659263974758,37.352846224439929,38.07509729881366,37.290412487096205,34.998791789287282,31.20023520538723,25.894742735395653,19.082314379312947,10.762950137138773,0.93665000887335736,-10.396586005483414,-23.236757905931427,-37.583865692470795,-53.437909365101518,-70.798888923823483],[0.0082312829207324967,9.7720976738424667,18.029028178672888,24.779022797412011,30.022081530059808,33.758204376616305,35.987391337081419,36.70964241145515,35.924957599737695,33.633336901928772,29.83478031802872,24.529287848037143,17.716859491954438,9.3974952497802633,-0.42880487848515259,-11.762040892841924,-24.602212793289937,-38.949320579829305,-54.803364252460028,-72.164343811181993],[-1.3572236044377775,8.4066427864839568,16.663573291314378,23.413567910053501,28.656626642701298,32.392749489257795,34.621936449722909,35.34418752409664,34.559502712379185,32.267882014570262,28.46932543067021,23.163832960678633,16.351404604595928,8.0320403624217533,-1.7942597658436625,-13.127495780200434,-25.967667680648447,-40.314775467187815,-56.168819139818538,-73.529798698540503],[-2.722678491796259,7.0411878991254753,15.298118403955897,22.04811302269502,27.291171755342816,31.027294601899285,33.256481562364456,33.978732636738187,33.194047825020732,30.902427127211809,27.103870543311757,21.79837807332018,14.985949717237474,6.6665854750633002,-3.1597146532020588,-14.492950667558944,-27.333122568006956,-41.680230354546325,-57.534274027176934,-74.895253585898899],[-4.0881333791547689,5.6757330117669653,13.932663516597387,20.68265813533651,25.925716867984306,29.661839714540776,31.891026675005946,32.613277749379677,31.828592937662222,29.536972239853299,25.738415655953247,20.43292318596167,13.620494829878965,5.3011305877047903,-4.5251695405605687,-15.858405554917454,-28.698577455365466,-43.045685241904835,-58.899728914535444,-76.260708473257409],[-5.4535882665132505,4.3102781244084838,12.567208629238905,19.317203247978028,24.560261980625825,28.296384827182266,30.525571787647493,31.247822862021224,30.463138050303769,28.171517352494845,24.372960768594794,19.067468298603217,12.255039942520511,3.9356757003463372,-5.8906244279190787,-17.22386044227585,-30.064032342723863,-44.411140129263231,-60.265183801893954,-77.626163360615919],[-6.8190431538717604,2.9448232370499738,11.201753741880395,17.951748360619519,23.194807093267315,26.930929939823756,29.160116900288983,29.882367974662714,29.097683162945259,26.806062465136336,23.007505881236284,17.702013411244707,10.889585055162001,2.5702208129878272,-7.2560793152775886,-18.58931532963436,-31.429487230082373,-45.776595016621741,-61.630638689252464,-78.991618247974429],[-8.1844980412302419,1.5793683496914923,9.8362988545219139,16.586293473261037,21.829352205908833,25.565475052465302,27.794662012930473,28.516913087304204,27.732228275586749,25.440607577777826,21.642050993877774,16.336558523886197,9.5241301678034915,1.2047659256293173,-8.6215342026360986,-19.95477021699287,-32.794942117440883,-47.142049903980251,-62.996093576610974,-80.357073135332939],[-9.5499529285887519,0.21391346233298236,8.4708439671634039,15.220838585902527,20.463897318550323,24.200020165106793,26.429207125571963,27.151458199945694,26.366773388228239,24.075152690419316,20.276596106519264,14.971103636527687,8.1586752804449816,-0.16068896172919267,-9.9869890899946085,-21.32022510435138,-34.160397004799393,-48.507504791338761,-64.361548463969484,-81.722528022691449],[-10.915407815947262,-1.1515414250255276,7.105389079804894,13.855383698544017,19.098442431191813,22.834565277748283,25.063752238213453,25.786003312587184,25.001318500869729,22.709697803060806,18.911141219160754,13.605648749169177,6.7932203930864716,-1.5261438490877026,-11.352443977353118,-22.68567999170989,-35.525851892157903,-49.872959678697271,-65.727003351327994,-83.087982910049959],[-12.280862703305772,-2.5169963123840375,5.739934192446384,12.489928811185507,17.732987543833303,21.469110390389773,23.698297350854943,24.420548425228674,23.635863613511219,21.344242915702296,17.545686331802244,12.240193861810667,5.4277655057279617,-2.8915987364462126,-12.717898864711628,-24.0511348790684,-36.891306779516412,-51.238414566055781,-67.092458238686504,-84.453437797408469],[-13.646317590664225,-3.8824511997424906,4.3744793050879309,11.124473923827054,16.36753265647485,20.10365550303132,22.33284246349649,23.055093537870221,22.270408726152766,19.978788028343843,16.180231444443791,10.874738974452214,4.0623106183695086,-4.2570536238046657,-14.083353752070138,-25.416589766426796,-38.256761666874809,-52.603869453414177,-68.457913126045014,-85.818892684766979],[-15.011772478022735,-5.2479060871010006,3.009024417729421,9.7590190364685441,15.00207776911634,18.73820061567281,20.96738757613798,21.689638650511711,20.904953838794256,18.613333140985333,14.814776557085281,9.5092840870937039,2.6968557310109986,-5.6225085111631756,-15.448808639428592,-26.782044653785306,-39.622216554233319,-53.969324340772687,-69.823368013403524,-87.184347572125489],[-16.377227365381245,-6.6133609744595105,1.643569530370911,8.3935641491100341,13.63662288175783,17.3727457283143,19.60193268877947,20.324183763153201,19.539498951435746,17.247878253626823,13.449321669726771,8.1438291997351939,1.3314008436524887,-6.9879633985216856,-16.814263526787101,-28.147499541143816,-40.987671441591829,-55.334779228131197,-71.188822900762034,-88.549802459483999],[-17.742682252739755,-7.9788158618180205,0.27811464301240107,7.0281092617515242,12.27116799439932,16.00729084095579,18.236477801420961,18.958728875794691,18.174044064077236,15.882423366268313,12.083866782368261,6.778374312376684,-0.034054043706021275,-8.3534182858801955,-18.179718414145611,-29.512954428502326,-42.353126328950339,-56.700234115489707,-72.554277788120544,-89.915257346842509],[-19.108137140098208,-9.3442707491764736,-1.087340244346052,5.6626543743930711,10.905713107040867,14.641835953597337,16.871022914062507,17.593273988436238,16.808589176718783,14.51696847890986,10.718411895009808,5.4129194250182309,-1.3995089310644744,-9.7188731732386486,-19.545173301504065,-30.878409315860836,-43.718581216308849,-58.065689002848217,-73.91973267547894,-91.280712234200905],[-20.473592027456718,-10.709725636534984,-2.452795131704562,4.2971994870345611,9.5402582196823573,13.276381066238827,15.505568026703997,16.227819101077728,15.443134289360273,13.15151359155135,9.3529570076512982,4.0474645376597209,-2.7649638184229843,-11.084328060597159,-20.910628188862574,-32.243864203219346,-45.084036103667358,-59.431143890206727,-75.28518756283745,-92.646167121559415],[-21.839046914815228,-12.075180523893494,-3.8182500190630719,2.9317445996760512,8.1748033323238474,11.910926178880317,14.140113139345488,14.862364213719218,14.077679402001763,11.78605870419284,7.9875021202927883,2.682009650301211,-4.1304187057814943,-12.449782947955669,-22.276083076221084,-33.609319090577856,-46.449490991025868,-60.796598777565237,-76.65064245019596,-94.011622008917925],[-23.204501802173738,-13.440635411252003,-5.1837049064215819,1.5662897123175412,6.8093484449653374,10.545471291521807,12.774658251986978,13.496909326360708,12.712224514643253,10.42060381683433,6.6220472329342783,1.316554762942701,-5.4958735931400042,-13.815237835314178,-23.641537963579594,-34.974773977936366,-47.814945878384378,-62.162053664923747,-78.01609733755447,-95.377076896276435]],\"type\":\"surface\",\"x\":[-2.480144546381263,-2.2339782056751258,-1.9878118649689887,-1.7416455242628515,-1.4954791835567143,-1.2493128428505773,-1.0031465021444401,-0.75698016143830293,-0.51081382073216575,-0.26464748002602878,-0.018481139319891593,0.22768520138624559,0.47385154209238278,0.72001788279851997,0.96618422350465716,1.2123505642107943,1.4585169049169315,1.7046832456230687,1.9508495863292055,2.1970159270353431],\"y\":[64.299999999999997,69.463157894736838,74.626315789473679,79.78947368421052,84.952631578947376,90.115789473684202,95.278947368421058,100.4421052631579,105.60526315789474,110.76842105263158,115.93157894736842,121.09473684210528,126.2578947368421,131.42105263157896,136.58421052631581,141.74736842105264,146.91052631578947,152.07368421052632,157.23684210526318,162.40000000000001],\"opacity\":0.59999999999999998,\"name\":\"Modell-Ebene\",\"frame\":null}],\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.20000000000000001,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n## 6.6 Synthese und Interpretation der Felddaten\n\nDie Modellierung der Netto-Stickstoffveränderung ($dN$) über die gemessenen Sommerintervalle liefert ein klares phänomenologisches Bild. Im bereinigten Datensatz, in dem die Messintervalle zeitlich korrekt abgeglichen wurden, verliert das enzymatische Profil (die Hauptkomponenten PC1 und PC2) seine statistische Signifikanz als linearer Prädiktor. Stattdessen wird die Varianz der Stickstoffmassenbilanz im Feld signifikant und stark nicht-linear durch den kumulierten Niederschlag dominiert ($p < 0.001$). \n\nDie beobachteten Netto-Mineralisierungsraten verhalten sich im Wesentlichen wie ein physikalisches System, in dem moderate Niederschläge vom Boden gepuffert werden, während Extremereignisse zu einem quadratisch ansteigenden Auswaschungsverlust führen. Ein robustes biologisches Signal, welches auf eine enzymatische Steuerung der Netto-Mineralisierung im Makromaßstab hindeutet, lässt sich aus den vorliegenden Daten nicht sicher extrahieren.\n\nDas Ausbleiben messbarer Korrelationen zwischen den in-vitro Enzymaktivitäten und den in-situ Stickstoffflüssen lässt verschiedene Interpretationen zu:\n\n1.  **Hypothese 1: Dominanz makroskopischer Flüsse**\n    Es ist davon auszugehen, dass die schiere Masse des durch starken Sommerniederschlag verlagerten Stickstoffs (Auswaschung, Denitrifikation) so groß ist, dass sie jeglichen mikrobiologischen Netto-Beitrag überlagert. Das biologische Signal fungiert unter diesen Witterungsbedingungen lediglich als Rauschen innerhalb der dominanten physikalischen Massenbilanz.\n    \n2.  **Hypothese 2: Diskrepanz zwischen potenzieller und realer Aktivität**\n    Die Reaktionsplatten messen die enzymatische *Potenzialaktivität* unter laboroptimierten Bedingungen (Substratsättigung, optimale Pufferung). Im Feld sind diese Enzyme jedoch Limitationen durch Diffusion, Trockenheit und fehlende Substratverfügbarkeit unterworfen. Das Laborpotenzial lässt sich folglich nicht zwingend als reale Umsetzungsrate in die Feldskala übersetzen.\n\n3.  **Hypothese 3: Technische Varianz und Sensorrauschen**\n    Letztlich muss in Betracht gezogen werden, dass die in-situ Heterogenität des Bodens und methodische Varianzen des Assays (z.B. Transportbedingungen, Matrixeffekte) eine zu geringe methodische Wiederholbarkeit aufweisen. Ohne hinreichende Konsistenz misst die Methode primär stochastisches Rauschen, welches prinzipbedingt keine Korrelation zu den realen Nährstoffflüssen aufbauen kann.\n\n# 7. Saisonaler Ansatz: Erste vs. Letzte Messung\n\nAls alternativen Ansatz zur Intervall-basierten Modellierung betrachten wir nun ausschließlich die Nettoveränderung über die gesamte Vegetationsperiode. Hierbei verwenden wir lediglich die erste und die letzte Messung jeder Parzelle.\n\nDie Fragestellung lautet: Kann die saisonale Veränderung der Enzymaktivität ($\\\\Delta$PC1 und $\\\\Delta$PC2) die saisonale Stickstoff-Nettoveränderung ($dN$) erklären, wenn wir die Varianz durch Witterung ausschließen? Da der Niederschlag über die gesamte Saison für alle Parzellen im Versuch identisch ist, fungiert er im Querschnitt dieses Modells lediglich als Konstante und fällt somit als erklärende Variable weg. Die Enzymdynamik rückt dadurch völlig in den Fokus.\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear mixed model fit by REML. t-tests use Satterthwaite's method [\nlmerModLmerTest]\nFormula: dN_season ~ Delta_PC1 + Delta_PC2 + (1 | ParzNrFeld)\n   Data: df_season\n\nREML criterion at convergence: 161.5\n\nScaled residuals: \n     Min       1Q   Median       3Q      Max \n-1.69675 -0.35814  0.07112  0.25910  1.81828 \n\nRandom effects:\n Groups     Name        Variance Std.Dev.\n ParzNrFeld (Intercept) 1420.54  37.690  \n Residual                 53.52   7.316  \nNumber of obs: 20, groups:  ParzNrFeld, 10\n\nFixed effects:\n             Estimate Std. Error        df t value Pr(>|t|)    \n(Intercept) -91.26108   12.13208   9.29217  -7.522 3.03e-05 ***\nDelta_PC1    -0.07735    1.01701   8.10370  -0.076    0.941    \nDelta_PC2    -0.51399    1.86911   8.13157  -0.275    0.790    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nCorrelation of Fixed Effects:\n          (Intr) Dl_PC1\nDelta_PC1  0.120       \nDelta_PC2  0.026 -0.167\n```\n\n\n:::\n:::\n\n\nWie die Modellzusammenfassung zeigt, bleiben auch über die gesamte Saison hinweg die Veränderungen im Enzymprofil ($\\\\Delta$PC1 und $\\\\Delta$PC2) als Prädiktoren für die Stickstoffbilanz statistisch nicht signifikant ($p > 0.05$).\n\nWir können dies visuell überprüfen. Da der Niederschlag in dieser Betrachtung konstant ist, entspricht die saisonale Netto-Stickstoffveränderung ($dN$) direkt dem (unbereinigten) partiellen Residuum in Bezug auf den C/N-Shift. Wir tragen dieses gegen $\\\\Delta$PC2 auf:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](DEMO_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\nDies bestätigt unsere vorherigen Hypothesen: Auch bei Betrachtung des größtmöglichen Intervalls (gesamte Saison) ist das biologische Signal der Potenzial-Enzymmessung (Digit Soil) nicht ausreichend konsistent oder nicht dominant genug, um die verbleibende Varianz in der in-situ Stickstoffmassenbilanz zwischen den Parzellen signifikant zu erklären.\n\n",
    "supporting": [
      "DEMO_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/htmltools-fill-0.5.9/fill.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<script src=\"../site_libs/plotly-binding-4.12.0/plotly.js\"></script>\n<script src=\"../site_libs/typedarray-0.1/typedarray.min.js\"></script>\n<script src=\"../site_libs/jquery-3.5.1/jquery.min.js\"></script>\n<link href=\"../site_libs/crosstalk-1.2.2/css/crosstalk.min.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/crosstalk-1.2.2/js/crosstalk.min.js\"></script>\n<link href=\"../site_libs/plotly-htmlwidgets-css-2.25.2/plotly-htmlwidgets.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/plotly-main-2.25.2/plotly-latest.min.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}